SeisSol/SeisSol

- src/ResultWriter/WaveFieldWriter.cpp
- src/ResultWriter/WaveFieldWriter.h
- src/ResultWriter/WaveFieldWriterC.cpp
- src/ResultWriter/WaveFieldWriterF.f90
- src/ResultWriter/inioutput_seissol.f90
- src/Solver/Interoperability.cpp
- src/Solver/Interoperability.h
- src/Solver/f_ftoc_bind_interoperability.f90
The current fix makes it possible to define which variables are to be printed (as per the parameter file) when compiled using asyncio=none and asyncio=thread option.
> Fix for output flags

- src/ResultWriter/WaveFieldWriterF.f90
- src/ResultWriter/inioutput_seissol.f90
- src/Solver/f_ftoc_bind_interoperability.f90
To avoid warnings from GCC, the logical array has been converted to integer considering that no implicit casting occurs and then passing it to the C function through an integer to integer binding.
> Change logicals to integers

- SConstruct
- src/Initializer/MemoryManager.cpp
- src/Initializer/ini_seissol.f90
- src/Initializer/tree/LTSTree.hpp
- src/Initializer/tree/Layer.hpp
- src/Initializer/tree/Lut.hpp
- src/Numerical_aux/typesdef.f90
- src/Reader/readpar.f90
- src/ResultWriter/PostProcessor.cpp
- src/ResultWriter/PostProcessor.h
- src/ResultWriter/SConscript
- src/ResultWriter/WaveFieldWriter.cpp
- src/ResultWriter/WaveFieldWriter.h
- src/ResultWriter/WaveFieldWriterC.cpp
- src/ResultWriter/WaveFieldWriterExecutor.h
- src/SeisSol.h
- src/Solver/Interoperability.cpp
- src/Solver/Interoperability.h
- src/Solver/f_ftoc_bind_interoperability.f90
- src/Solver/time_stepping/TimeCluster.cpp
By setting the `integrateQuants` flag to `yes` while compiling we can enable the computation and storage of 1st order time integration of the variables.
To enable or disable a variable for computation and storage a new section has been incorporated in the parameter file. The following example illustrates the new section:
```
&Postprocessing
IntegrationMask = 0 1 0 1 1 0 0 1 1  ! Integrate and output these vars
/
```
In this example, the variables `sigma_xx`, `sigma_xz`, `sigma_zz` and `u` will not be integrated and stored.
> Integrate quantities

- src/Checkpoint/Manager.h
- src/ResultWriter/FaultWriter.h
- src/ResultWriter/FreeSurfaceWriter.h
- src/ResultWriter/WaveFieldWriter.h
This fixes some pinning issues with the asyn IO.
Old behavior: I/O thread is pinned to some thread, depending on the implementation in the async library.
New behavior: I/O thread is pinned to threads that are not utilized by OpenMP and thus uses identical pinning as the communication thread.
Related changes in the ASYNC library are [here](https://github.com/TUM-I5/ASYNC/commit/5a55cdf94fad642232e5c48acd92beea8542c3ae)
> Fix pinning for async i/o.

- .gitmodules
This is a first step towards a repository that allows us to clone SeisSol recursively with
either ssh or https without worrying about changing the .gitmodules file manually.
This is accomplished by using relative paths for submodules.
Before this has a large effect, we'd need to update all dependencies.
Nevertheless, this is a good step towards a cleaner repository.
> Use relative path for submodules.

- preprocessing/science/rconv/src/SRF.cpp
The multiple use of the variable name caused a redeclaration error during the compilation of rconv.
This pull request fixes this issue.
> Fix rconv redeclaration error

- src/Geometry/MeshReaderCBinding.f90
when one supplies a mesh without dynamic rupture surfaces although dynamic rupture was declared in the parameter file.
Otherwise SeisSol will crash a few moments later and one does not see why in the first place.
> Include an error message, 

- src/Geometry/MeshReaderCBinding.f90
as it causes too much trouble.
This has been tested for the TPV12 scenario.
> Remove the error "Did not find dynamic rupture surfaces"

- Documentation/point-source-older-implementation.rst
- src/Initializer/dg_setup.f90
- src/Numerical_aux/typesdef.f90
- src/Reader/readpar.f90
- src/Solver/Interoperability.cpp
- src/Solver/Interoperability.h
- src/Solver/f_ftoc_bind_interoperability.f90
- src/Solver/time_stepping/TimeCluster.cpp
- src/SourceTerm/Manager.cpp
- src/SourceTerm/Manager.h
- src/SourceTerm/PointSource.cpp
- src/SourceTerm/PointSource.h
- src/SourceTerm/typedefs.hpp
- src/tests/Physics/PointSource.t.h
Until now it was not possible to use point sources acting on the velocity components directly. This pull request adds this new feature. 
The feature is implemented for the old version of point sources (Type = 50). After the moment tensor block you can now specify an optional velocity component for the three space dimension.
The feature was tested against an analytic solution. The force is located at the origin and acting in direction (1, 1, 0). The time history is a Ricker impulse. Receivers are placed at (0.0, 0.0, 500.0), (0.0, 500.0, 0.0), (500.0, 0.0, 0.0). See attached pictures for comparisons between the analytic and numerical solution. 
Note that the resolution is quite rough (66,000 cells) so sharp features are not well resolved. Nevertheless, the results show, that the …
> Add force sources

- Documentation/kinematic.rst
The double quotation marks are wrong and will result in wiled errors.
> fix a typo in the command rconv

- Documentation/dynamic-rupture.rst
- src/Numerical_aux/create_fault_rotationmatrix.f90
- src/Physics/Evaluate_friction_law.f90
- src/Physics/NucleationFunctions.f90
- src/Physics/SConscript
- src/Physics/ini_model_DR.f90
- src/Reader/readpar.f90
- src/ResultWriter/faultoutput.f90
This new friction law allows imposing Slip (via SR) on the boundary condition.
The most direct use is (a very expensive way) for computing the final traction distribution from a slip distribution (potential application for the Norcia earthquake).
> Sr imposed on dr boundary

- .travis.yml
Currently travis fails because downloading the dependencies fails (resource doesn't exist anymore). Quick fix: move it to lrz-cloud.
> Fix travis, deps now self-hosted

- src/Model/common.hpp
- Always compute the Riemann solver in double precision (and store result in single/double)
- Exit with an error when the matrix of eigenvectors is not invertible. The computed inverse would be useless anyway.
> Improve computation of Riemann solver for single precision

- CMakeLists.txt
-qopenmp enables multi-threading in case of SeisSol is supposed to get compiled with Intel compiler
> -qopenmp flag has been added to the intel compiler

- src/Model/common.hpp
The matrix R has a bad condition number. If we scale the eigenvectors, which span the null space, we get a better condition number.
> Improve the condition number of the eigenvalue matrix R 

- Documentation/compilation.rst
On some machines we encountered problems with netCDF linking. The --disable-dap flag solves these issues. As we do not need netCDF with dap support, this can be the standard.
> Add --disable-dap for netcdf compilation

- postprocessing/visualization/receiver/src/View.py
- postprocessing/visualization/receiver/src/Waveform.py
Hi, I have to compare traces of SeisSol with the ones from collaborators who use other codes. Sometimes it is unnecessarily complicated to think about comparisons of magnitudes and we are just interested in the wave form. That's why I added a normalize button to viewrec. Maybe that's useful for the one or other...
> Add normalize button to Viewrec

- Documentation/compilation.rst
GCC-8 does not support all needed target, e.g. on supermuc-ng:
```
ga24dib3@login02:~> module switch gcc/8
ga24dib3@login02:~> gcc --target-help | grep -o skylake-avx512
```
```
ga24dib3@login02:~> module switch gcc/9 
ga24dib3@login02:~> gcc --target-help | grep -o skylake-avx512
skylake-avx512
skylake-avx512
```
> Require gcc 9

- CMakeLists.txt
Removes this warning:
> 
> CMake Warning at CMakeLists.txt:142 (find_package):
>   By not providing "FindYAML-CPP.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "YAML-CPP",
>   but CMake did not find one.
> 
>   Could not find a package configuration file provided by "YAML-CPP"
>   (requested version 0.5.3) with any of the following names:
> 
>     YAML-CPPConfig.cmake
>     yaml-cpp-config.cmake
> 
>   Add the installation prefix of "YAML-CPP" to CMAKE_PREFIX_PATH or set
>   "YAML-CPP_DIR" to a directory containing one of the above files.  If
>   "YAML-CPP" provides a separate development package or SDK, be sure it has
>   been installed.
> Remove warning when compiling yaml on submodules

- postprocessing/visualization/tools/extractDataFromUnstructuredOutput.py
- postprocessing/visualization/tools/recreateXdmf.py
Some minor improvement to this script for extracting time steps:
- default to hdf5 and float as it drastically reduces file size.
- write in the current folder and not in the folder of the input file.
- add `last` option to write the last time step without knowing the index.
-fix for `-` sign in prefix
> minor improvement to extractDataFromUnstructuredOutput.py

- CMakeLists.txt
- Documentation/supermuc.rst
- cmake/FindNUMA.cmake
- cmake/process_users_input.cmake
- src/Parallel/Pin.cpp
- src/Parallel/Pin.h
- src/SeisSol.cpp
Our current pinning method does not work for the GCC compiler.
Or rather, with its standard OpenMP runtime. It sets the affinity mask for the entire process from the OpenMP pinning mask at the beginning of the process. For intel/clang compiler, this only happens after the first OpenMP call.
This PR implements a different strategy:
- Find affinity mask for all OpenMP threads on every process
- Find affinity mask for all OpenMP threads on every *node*
- Pin communication thread to all cores that are not used by OpenMP.
Furthermore, if the option NUMA_AWARE_PINNING is used, we only pin the communication thread to the cores that are not used by OpenMP and that are in on of the numa domains used by OpenMP.
This option needs libnuma which is available basically everywhere (module numactl most …
> Fix pinning for GCC

- src/Equations/viscoelastic2/Model/datastructures.hpp
- src/Geometry/MeshReaderCBinding.f90
- src/Initializer/ini_seissol.f90
- src/Initializer/time_stepping/common.hpp
- src/Numerical_aux/typesdef.f90
- src/Physics/ini_model_DR.f90
- src/Reader/readpar.f90
- src/ResultWriter/energies.f90
- src/ResultWriter/faultoutput.f90
- src/Solver/Interoperability.cpp
- src/Solver/calc_seissol.f90
- src/Solver/f_ctof_bind_interoperability.f90
* updated reference to utils and xdmfwriter submodules
The majority of warnings are coming from the following 3 sources:
- Variable<real[kernels::size<tensor::Qane>()]> dofsAne;
- double omega[NUMBER_OF_RELAXATION_MECHANISMS];
- double theta[NUMBER_OF_RELAXATION_MECHANISMS][3];
It is going to be addressed by a dedicated PR
> Removed some warnings (gcc, gfortran)

- CMakeLists.txt
As mentioned in #330, currently SeisSol fails with a very strange error, when an output file is not found. This PR should address that issue.
> Update xdmf writer.

- CMakeLists.txt
- auto_tuning/proxy/src/proxy_seissol_allocator.hpp
- cmake/process_users_input.cmake
- src/Geometry/MeshReaderCBinding.f90
- src/Geometry/MeshReaderFBinding.cpp
- src/Initializer/LTS.h
- src/Initializer/MemoryManager.cpp
- src/Initializer/MemoryManager.h
- src/Initializer/dg_setup.f90
- src/Reader/readpar.f90
- src/Solver/Interoperability.cpp
- src/Solver/Interoperability.h
- src/Solver/f_ftoc_bind_interoperability.f90
- src/Solver/time_stepping/MiniSeisSol.cpp
- src/Solver/time_stepping/MiniSeisSol.h
- src/Solver/time_stepping/TimeCluster.cpp
- src/Solver/time_stepping/TimeCluster.h
- src/Solver/time_stepping/TimeManager.cpp
- src/Solver/time_stepping/TimeManager.h
Note: This PR is very much still in progress.
This PR removes the compile time option for plasticity and replaces it with a runtime option.
By using templates + constexpr if, we can create two optimized paths for the neighbor integration kernel: One with plasticity, one without.
In this way, this change comes without much (or any) performance cost.
This is very poorly tested.
@ravil-mobile Can you please have a look at the GPU version? I've just deleted the USE_PLASTICITY macros in your kernels/init. I think it should be fine to just do an i`f(usePlasticity)` in some places but I wasn't really sure. Also, I have currently no GPU, so I can't test this.
> Remove compile option for plasticity

- postprocessing/visualization/receiver/src/View.py
The receiver viewer crashes in the computation of the L2 error if the waveforms don't have the same length (due to forbidden extrapolation in scipy). This PR ensures that the time union is bounded w.r.t. to the waveforms' time interval.
> Fix crash in viewrec

- cmake/cpu_arch_flags.cmake
These are the flags that we used for our SC paper submission. They are tested.
We need to use Intel compiler currently because of #256.
> Fix flags for AMD Rome when using Intel compiler.

- azure-pipelines-seissol-template.yml
- src/Geometry/MeshReaderCBinding.f90
- src/Geometry/allocate_mesh.f90
- src/Initializer/dg_setup.f90
- src/Initializer/ini_optionalfields.f90
- src/Initializer/ini_seissol.f90
- src/Numerical_aux/dgbasis.f90
- src/Numerical_aux/operators.f90
- src/Numerical_aux/quadpoints.f90
- src/Physics/Evaluate_friction_law.f90
- src/Reader/read_backgroundstress.f90
- src/ResultWriter/energies.f90
- src/ResultWriter/faultoutput.f90
- src/ResultWriter/ini_faultoutput.f90
- src/ResultWriter/output_rupturefront.f90
- src/ResultWriter/receiver.f90
- src/ResultWriter/receiver_hdf.f90
- src/Solver/calc_deltat.f90
- src/Solver/close_seissol.f90
- src/Solver/mpiexchangevalues.f90
- src/seissolxx.f90
I changed the `call exit(134)` to `call MPI_ABORT(MPI%commWorld, 134)`.
Same files as Sebastian previous PR.
Then I added the `USE mpi_f08` at the beginning of each file modified.
But, then I removed it in files where the compilation was complaining (because MPI_COMM_WORLD was already included in another module?).
(in the process of fixing the compilation, I changed some of the MPI_COMM_WORLD to MPI%commWorld, which should be equivalent, right?).
> exit to MPIABORT

- postprocessing/visualization/tools/extractDataFromUnstructuredOutput.py
I just added some arguments to the script to extract a subset of the paraview output given coordinate ranges.
(was useful for processing the Palu surface output, might be useful for future setups).
I also changed a few things to fix errors identified by flake8.
Example of use:
```
python extractDataFromUnstructuredOutput.py /hppfs/work/pr45fi/ga24dib3/shared/2021-04-29_17-00_0/run_0/output/Sulawesi_WL_Batv1_CFL04b-surface.xdmf --Data U V W --do 100 --precision double --add resampled100s --xfilter -32000.0 24000.0 --yfilter -46000.0 58000.0 --no_ocean
```
Thomas.
> add filters to extractDataFromUnstructuredOutput.py

- src/Numerical_aux/dgbasis.f90
- src/Numerical_aux/operators.f90
- src/Reader/read_backgroundstress.f90
- src/Reader/readpar.f90
It turns out that using MPI_f08 breaks the compilation with openmpi (at least 3.1.4).
I then remove MPI_f08 by passing the MPI structure in operator and dgbasis.f90.
> introduce MPI structure in operator and dgbasis

- src/Physics/Evaluate_friction_law.f90
- src/ResultWriter/faultoutput.f90
Hi, following a question of Kadek about positive Pn0 in SeisSol, I've been looking a the friction laws and came to the conclusion that Rate and State friction laws currently wrongly handle tension, contrary to linear slip weakening.
Let me know what you think of the changes I propose to fix that.
We also need to check the effect of these changes on both TP and tpv104 benchmarks.
Thomas.
> fix fault strength when tension with Rate and State frictions

- postprocessing/science/GroundMotionParametersMaps/ComputeGroundMotionParametersFromSurfaceOutput_Hybrid.py
- postprocessing/science/GroundMotionParametersMaps/SupermucNGCommandFileComputeGroundMotions.sh
Changes to ComputeGroundMotionParametersFromSurfaceOutput_Hybrid.py:
- add option to filter waveforms 
- use np.gradient to differentiate, ~~np.cumsum to integrate~~
- add option to compute CAV (cumulated accumulated velocity)
- refactor based on flake8 recommandations.
> compute ground motion: CAV, filtering, refactoring 

- src/ResultWriter/AnalysisWriter.cpp
- src/ResultWriter/AnalysisWriter.h
- src/Solver/Interoperability.cpp
This PR adds an CSV error writer. After running a scenario with an analytical solution, it also writes the output to a csv file (using the path given for other output options).
The files (note: truncated!) looks roughly like this:
```
variable,norm,error
0,L1,0.326084
0,L2,0.129683
0,LInf,0.251285
1,L1,0.307356
1,L2,0.128929
1,LInf,0.251285
2,L1,0.350589
2,L2,0.133231
2,LInf,0.251285
3,L1,0.0129171
3,L2,0.00674716
3,LInf,0.0248785
```
> Add csv error output

- CMakeLists.txt
- cmake/process_users_input.cmake
Can use option -DADDRESS_SANITIZER_DEBUG to link with address sanitzer when in debug mode.
https://en.wikipedia.org/wiki/AddressSanitizer can help a lot with finding memory leaks and related issues.
> Add option to enable address sanitzer in debug mode

- Documentation/adapting-the-cad-model-resolution-using-gocad.rst
- Documentation/cad-models.rst
- Documentation/generating-a-cad-model-using-gocad-basic-tutorial.rst
- Documentation/remeshing-the-topography.rst
- Documentation/simmodelerCAD-workflow.rst
Small PR that precises the tutorials:
- use python3 instead of python when calling the cad scripts 
- precise path to Examples
(or maybe it would be preferable to add a shebang (`#!/usr/bin/env python3`) to all these scripts?)
> precise tutorial with python3, precise paths

- Documentation/free-surface-output.rst
- src/ResultWriter/FreeSurfaceWriterExecutor.cpp
Calling surface velocity uvw and displacements UVW might pose a problem for case insensitive operating systems.
(Windows, and maybe Mac. Note that Bo and Duo do not have problem with case sensitivity on their mac).
> change variable names of free surface output

- src/Initializer/tree/InterfaceHelper.hpp
- src/Reader/AsagiReader.h
Otherwise, searches first in system header files and not in sub-
modules
https://stackoverflow.com/a/21594
> Fix include type for easi headers

- src/Physics/Evaluate_friction_law.f90
the strength decrease during nucleation should account for the substep time increment.
> fix minor issue on LSW forced rupture

- generated_code/NodalBoundaryConditions.py
- generated_code/aderdg.py
- generated_code/viscoelastic2.py
- src/Equations/elastic/Kernels/GravitationalFreeSurfaceBC.cpp
- src/Equations/elastic/Kernels/GravitationalFreeSurfaceBC.h
- src/Equations/elastic/Kernels/Time.cpp
- src/Equations/elastic/Kernels/TimeBase.h
- src/Kernels/Time.h
- src/Solver/time_stepping/TimeCluster.cpp
Old way: Use RK to compute the ODE that defines the displacement
New way: Use ADER-magic to compute the Taylor series of the displacement directly and evaluate it at end of timestep and compute integral of displacement. Does this in-place without storing all coefficients. A lot faster, and of arbitrary order.
Draft because: Needs to be tested for realistic application, flop counter needs to be checked (@sebwolf-de if you're bored ;)).
I've already verified that it works for convergence tests. I get the exact same results but faster.
> Optimize computation of gravitational boundary condition

- Documentation/supermuc.rst
I adjusted the documentation for compiling SeisSol on SuperMUC-NG (https://seissol.readthedocs.io/en/latest/supermuc.html#building-seissol).
Double precision should be used as default instead of single precision (-DPRECISION=double instead of -DPRECISION=single).
> update Building SeisSol on SuperMUC-NG - use double precision

- src/Physics/Evaluate_friction_law.f90
- src/Solver/calc_seissol.f90
Compiling the code on GCC 10.2.0 resulted in six warnings in the Fortran section of SeisSol.
Five concerned variable conflicts on src/Physics/Evaluate_friction_law.f90
and one was an incorrect comment marker in calc_seissol.f90.
> Removing warnings from the Fortran section of SeisSol.

- Documentation/compilation.rst
- Documentation/supermuc.rst
These modules work with the new spack environment on supermuc ng. Note that you need to recompile everything (at least ASAGI, easi, SeisSol).
Not sure why it works with this yaml-cpp module: It's version 0.7 and we search for 0.6.3 explicitly. However, easi finds it and links with it correctly.
https://github.com/TUM-I5/ASAGI/pull/12 needs to be merged beforehand, otherwise ASAGI does not find netcdf.
> Update SNG modules.

- Documentation/asagi.rst
- Documentation/compilation.rst
- Documentation/supermuc.rst
fixes Asagi compilation on supermuc described twice.
Removed reference to precompiles ASAGI and libxmm on supermuc (in the end, I don't think it is a significant time gain).
> improve compilation documentation

- src/Equations/viscoelastic/Kernels/GravitationalFreeSurfaceBC.h
I just found out that the `viscoelastic` compilation (without the `2`) failed. Here is an easy fix.
> Fix viscoelastic compilation

- gitlab-cpu-pipeline.yml
I created a slip distribution without the need for ASAGI to test FL 33 and 34 in the gitlab pipeline. See also the changes here: https://github.com/7bits-register/precomputed-seissol/commit/fd9f4bfaa21d521c46ba42341ffa4c32137cbd56 
The Pipeline has passed before I created the PR ;-)
> dr/cpp: add FL 33 and 34 to the pipeline again

- Documentation/fault-tagging.rst
Clarify that "boundaryCondition tag="3"" is equivalent to "dynamicRupture" to avoid confusion
> Mathilde / Update fault-tagging.rst

- src/Initializer/dg_setup.f90
With this fix, we set the neighbor material correctly for all internal faces. In particular, this fixes the problem that at dynamic rupture interfaces, we used the wrong impedances to compute the Godunov state.
Verification: See attached picture of receiver 3 for the TPV6 benchmark. Blue: master, orange: this fix.
Estimated arrival time of the wave is ~3.8s (see SCEC screenshot)
> Copy neighbor material also in case of dynamic rupture BC

- src/ResultWriter/ReceiverWriter.cpp
Within the free surface output of SeisSol we have the following output variables:
v1, v2, v3: ground velocities, x y and z components
u1, u2, u3: ground displacements, x y and z components
So far the three particle velocities within the off-fault receiver output files were named u, v, w. I would like to rename them to v1, v2, v3 for better consistency.
> adjust receiver variable names for better consistency

- generated_code/DynamicRupture.py
- gitlab-gpu-pipeline.yml
- src/DynamicRupture/FrictionLaws/BaseFrictionLaw.h
- src/DynamicRupture/FrictionLaws/FrictionSolver.cpp
- src/DynamicRupture/FrictionLaws/FrictionSolver.h
- src/DynamicRupture/FrictionLaws/FrictionSolverCommon.h
- src/DynamicRupture/FrictionLaws/GpuImpl/GpuBaseFrictionLaw.cpp
- src/DynamicRupture/FrictionLaws/GpuImpl/GpuBaseFrictionLaw.h
- src/DynamicRupture/FrictionLaws/GpuImpl/GpuFrictionSolver.h
- src/DynamicRupture/Misc.h
- src/Initializer/typedefs.hpp
- src/Kernels/DynamicRupture.cpp
- src/Kernels/DynamicRupture.h
- src/ResultWriter/EnergyOutput.cpp
- src/ResultWriter/EnergyOutput.h
- src/Solver/time_stepping/TimeCluster.cpp
This PR contains a draft refactoring of the DR energy output computations. The implementation became common for CPUs and GPUs. The data structured were aligned.
TODO:
- ~remove unnecessary yateto kernels which we do not need anymore~
- ~adjust flop counters~
- rename variables `aPlus`, `aMinus`, `bPlus`, `bMinus` 
- ~`spaceWeights` are not changing during computations and thus need to be copied to GPUs only once~
- ~`inline real magnitude` can be generalized for an N-dimensional vector with templates~
> Refactored DR Energy Output computations

- src/DynamicRupture/FrictionLaws/GpuImpl/LinearSlipWeakening.h
- src/DynamicRupture/FrictionLaws/LinearSlipWeakening.h
- src/DynamicRupture/Initializers/ImposedSlipRatesInitializer.cpp
- src/DynamicRupture/Output/DataTypes.hpp
1. I had some problems with unaligned data on SuperMUC-NG. The aligned allocator fixes that.
2. Use std::clamp to avoid `min(max(...))` constructs.
> Small improvements: std::clamp, aligned_allocator

- Documentation/frontera.rst
- Documentation/index.rst
- Documentation/installing-dependencies.rst
- Documentation/shaheen.rst
Document seissol-env installation on Frontera.
You will say, it starts to be a catalog of supercomputer installations.
But there are always tricks (e.g., the module in the compilers.yaml) that were not detailed before.
> Document Frontera seissol-env

- Documentation/frontera.rst
- Documentation/shaheen.rst
`cc` in small letters does not have an effect, which is not a big problem, since we do not use the c compiler, but for completeness, I'd correct it.
> Fix typo in Frontera doc

- gitlab-cpu-pipeline.yml
- gitlab-gpu-pipeline.yml
- Created a kubernetes cluster on LRZ compute cloud with two nodes: master (10 cores) & worker (20 cores)
- Set `static` CPU Management Policies to enforce `Guaranteed` Quality of Service Class which sets `cpu-set` for each pod (container)
- installed gitlab-runner with `helm chart`: 4 cores, 10 gb of RAM for each pod, concurrency level 5
- switched our GPU pipeline to a GPU kubernetes gitlab runner provided by TUMI05
Notes for the next CI update:
- let's use `make install` to copy all executables and libraries to a specific folder which we will copy to the next stage as `artifacts`
- @sebwolf-de, I guess we need to use checkpoints to drastically reduce run-times for `tpv*` tests
- move recorded solutions from `https://github.com/7bits-register/precomputed-seissol.git` to a sub-project of …
> Switched CPU and GPU pipelines to gitlab-kubernetes-runners

- Documentation/tpv24.rst
There was a typo in the table showing the static and dynamic friction coefficient values: static was 0.12 and dynamic was 0.18, which should be the opposite. Fixed the values in the table accordingly.
> Fixing typo in TPV24 example

- src/DynamicRupture/FrictionLaws/FrictionSolver.h
- src/DynamicRupture/Initializers/RateAndStateInitializer.cpp
* Found a way to easier initialize the space weights
* Throw an error, if the state variable is negative
> negative state variable check (Fix 668) + updated space weights initialization

- auto_tuning/proxy/src/proxy_seissol.cpp
- src/Kernels/Receiver.cpp
- src/Monitoring/FlopCounter.cpp
- src/Monitoring/FlopCounter.hpp
- src/ResultWriter/inioutput_seissol.f90
- src/SeisSol.h
- src/Solver/Interoperability.cpp
- src/Solver/Interoperability.h
- src/Solver/Simulator.cpp
- src/Solver/f_ftoc_bind_interoperability.f90
- src/Solver/time_stepping/TimeCluster.cpp
* Write Flop Counter per node to csv file for detailed analysis.
* Compute current performance (since last syncpoint) instead of average since the beginning. This way you better see changes in performance.
* Better output to stdout.
> Flop Counter Improvements

- gitlab-cpu-pipeline.yml
Sometimes, we have this error in the CI, which is easily fixed by a manual "retry". 
There's actually a gitlab CI feature, which does that automatically, to make life easier for all of us...
> Retry CI if job has failed

- src/Monitoring/FlopCounter.cpp
Zero flops is a valid amount of flops for operations on empty clusters
> Remove asserts for zero updates - broken for empty clusters

- src/Numerical_aux/typesdef.f90
- src/ResultWriter/EnergyOutput.cpp
- 60 is sometimes not enough, in particular because scratch (/hppfs/scratch/0A/di73yeq4/) takes already half of it.
- nan checker on energies make sense as energies traverse the all mesh (and we got them for free).
(I also applied clang-format on the file)
> increase size of OutputFile, add nan checker

- Documentation/off-fault-receivers.rst
The option to set `ReceiverOutputInterval ` was not yet specified in the Off fault receivers documentation (https://seissol.readthedocs.io/en/latest/off-fault-receivers.html).
> update receiver documentation

- Documentation/behind_firewall.rst
- Documentation/energy-output.rst
- Documentation/parameters.par
- postprocessing/validation/compare-energies.py
- src/Numerical_aux/typesdef.f90
- src/Reader/readpar.f90
- src/ResultWriter/EnergyOutput.cpp
- src/ResultWriter/EnergyOutput.h
- src/ResultWriter/inioutput_seissol.f90
- src/Solver/Interoperability.cpp
- src/Solver/Interoperability.h
- src/Solver/f_ftoc_bind_interoperability.f90
- src/Solver/time_stepping/GhostTimeCluster.cpp
- Add parameter `ComputeVolumeEnergiesEveryOutput` to compute and print volume energies only once every ComputeVolumeEnergiesEveryOutput * EnergyOutputInterval.
(most useful when the Moment rate is needed at a high sampling rate, or when running seissol GPU).
Note that this leads to a change in the format of the prefix-enery.csv files
- Fix the documentation of pip behind proxy.
> Add possibility to output volume energies less frequently than fault energies

- src/Parallel/MPI.h
Exclusive_scan has pretty bad compiler support, e.g. does not work on Frontera (Icc 19.1)
> Remove exclusive_scan due to bad complier support

- src/Initializer/InputAux.hpp
- src/Initializer/MemoryManager.h
- src/Parallel/MPI.h
- src/ResultWriter/ClusteringWriter.cpp
- src/ResultWriter/ClusteringWriter.h
- src/SeisSol.cpp
- src/Solver/time_stepping/TimeCluster.cpp
- src/Solver/time_stepping/TimeCluster.h
- src/Solver/time_stepping/TimeManager.cpp
- src/sources.cmake
This PR adds a writer that outputs information about the (local) clusters, including their id, size, number of dynamic rupture faces, etc.
Furthermore, it uses a "profilingid" for the loop information, which allows us to differentiate between the costs of computing copy and interior clusters.
This is useful, as copy clusters are typically quite small and thus have larger loops which do not gain that much from shared memory parallelization.
> Add clustering writer

- Documentation/cookbook_overview.rst
The link https://seissol.readthedocs.io/en/latest/compilation.html is broken, should it perhaps point to https://seissol.readthedocs.io/en/latest/compiling-seissol.html ?
> Fix broken link in cookbook_overview.rst

- Documentation/parameters.par
- src/Initializer/MemoryManager.h
- src/Monitoring/LoopStatistics.cpp
- src/Monitoring/LoopStatistics.h
- src/Reader/readpar.f90
- src/Solver/Simulator.cpp
- src/Solver/time_stepping/TimeCluster.cpp
- src/Solver/time_stepping/TimeCluster.h
- src/Solver/time_stepping/TimeManager.cpp
- src/Solver/time_stepping/TimeManager.h
This PR has the following improvements for the profiling:
- Skip loops of size zero, arising from clusters with size 0 (may improve performance slightly, handled differently for predict/correct due DR scheduling, not done for some GPU kernels)
- Fix time spent in DR (last PR did not work, missed an MPI_Reduce)
-  Use int64 as offset for nc files, required for long, large-scale simulations
- Add config option in parameters.par, use better output name
The profiling is not documented on purpose, as it should not used by non-developers. I'll add some analysis scripts later (with documentation).
@ravil-mobile I didn't add skipping of zero-sized loops for all kernels for GPUs. The profiling works without this but you might add this later to improve performance slightly.
> Improve profiling

- preprocessing/meshing/cube_c/src/main.cpp
This PR adds the possibility to define seperate boundary conditions, 2 for each dimension.
Instead of calling for example  `./cubeGenerator -b 6 -x 2 -y 2 -z 2 --px 1 --py 1 --pz 1 -o <filename> -s 2`, we can define seperate boundary conditions as follows:
`./cubeGenerator --minx 6 --maxx 6 --miny 6 --maxy 6 --minz 6 --maxz 6 -x 2 -y 2 -z 2 --px 1 --py 1 --pz 1 -o <filename> -s 2`.
Partial use of the seperate boundary conditions is also possible, e.g. `./cubeGenerator -b 6 --minx 7 --maxx 7 -x 2 -y 2 -z 2 --px 1 --py 1 --pz 1 -o <filename> -s 2` would override only the boundary conditions of the x dimension.
Specifying the general boundary condition `-b <condition>` works as before. The seperate boundary options simply use the value passed for the general boundary condition if the …
> Added additional cube boundary options

- auto_tuning/proxy/src/proxy_seissol_device_integrators.hpp
- src/DynamicRupture/FrictionLaws/GpuImpl/FrictionSolverDetails.cpp
- src/DynamicRupture/FrictionLaws/GpuImpl/RateAndState.h
- src/hip.cmake
* fixed warning in rocm@5.4>= (--offload-arch)
> Fixed `0` byte allocation in sycl (dr)

- src/Initializer/InitProcedure/Init.cpp
- src/Initializer/InputParameters.cpp
- src/Parallel/AcceleratorDevice.cpp
- src/SeisSol.cpp
- src/Solver/time_stepping/CommunicationManager.cpp
* set the device at the very top of seissol (before any possible MPI_Init)
* adds GPU binding to the comm thread (important for UCX)
* fixed printing of info data to the console
Note: this PR comes together with https://github.com/SeisSol/Device/pull/25
> Set device context for the communication thread

- src/DynamicRupture/Parameters.h
When using FrictionLawType::ImposedSlipRatesYoffe or FrictionLawType::ImposedSlipRatesGaussian, strength is set to 0 (https://github.com/SeisSol/SeisSol/blob/master/src/DynamicRupture/Output/ImposedSlipRates.hpp#L9), and therefore computed updated Tractions (https://github.com/SeisSol/SeisSol/blob/master/src/DynamicRupture/Output/ReceiverBasedOutput.cpp#L308, before they are reset, https://github.com/SeisSol/SeisSol/blob/master/src/DynamicRupture/Output/ImposedSlipRates.hpp#L17) and associated derived SR (https://github.com/SeisSol/SeisSol/blob/master/src/DynamicRupture/Output/ReceiverBasedOutput.cpp#L327) are wrong when calculated with SlipRateOutputType=1.
On the other hand, the SR value calculated from the velocities on both sides of the faults are correct.
> Change slipRateOutputType to 0 when using a friction law with imposed slip rate 

- postprocessing/visualization/receiver/src/Filters.py
Update quantity list, if different receivers have different quantities, e.g. fault receivers and off-fault receivers.
> Improve 'Pick components' filter

- src/Initializer/InputParameters.cpp
- src/main.cpp
This PR makes `RFilename` in the parameters file optional again (and not mandatory). Also, the vertex weight parameters are now read correctly.
A legacy FORTRAN definition was also removed.
> Fix some input parameters (incl. RFileName)

- src/Initializer/InitProcedure/InitIO.cpp
- src/ResultWriter/ReceiverWriter.cpp
- src/ResultWriter/ReceiverWriter.h
> Fix Receiver Output Length Error

- .ci/format.sh
- src/DynamicRupture/Output/Builders/ElementWiseBuilder.hpp
- src/SeisSol.cpp
- src/SeisSol.h
- src/main.cpp
Also
* Updated reference to device
* applied formatting to `SeisSol.cpp`, `SeisSol.h` and `main.cpp`
* edited info printing in `ElementWiseBuilder.hpp`
> Moved device initialization to the very beginning

- src/Kernels/PointSourceClusterOnDevice.cpp
- src/Kernels/PointSourceClusterOnDevice.h
- src/SeisSol.cpp
- src/Solver/time_stepping/TimeCluster.h
- src/Solver/time_stepping/TimeManager.cpp
- src/Solver/time_stepping/TimeManager.h
- src/SourceTerm/Manager.cpp
- src/SourceTerm/PointSource.h
- src/SourceTerm/typedefs.hpp
Hi Carsten (@uphoffc), Here are my changes which I would like to push to your branch `carsten/point-source-gpu`
- OpenSYCL doesn't work with `queue.parallel_for`. I switched the implementation to `submit`
- applied `clang-format` to `src/SourceTerm/PointSource.h`. Probably I need to do the same for `PointSource.cpp` and add them to the watchlist in the CI pipeline.
Issues:
- @uphoffc, I am not sure that the numerics is correct. I will do some tests. Have you tested it?
-  The destructor of `PointSourceClusterOnDevice` needs to before exiting `main` function. Probably `PointSourceClusterOnDevice` belongs to `TimeCluster` which belongs to `TimeManager` which belongs to `SeisSol` which is a static object. If it is not done then the following problem occurs
```
Thu Jun 08 17:25:45, Info: …
```
> Adapted the device::UsmAllocator

- src/main.cpp
The line below fails to compile if the MPI implementation defines the namespace MPI. This PR fixes compilation by making the reference to the seissol namespace explicit.
> Fix namespace

- src/Initializer/InitProcedure/InitModel.cpp
Fixes #890. I.e. make plasticity work again.
The reason was: the `tv` parameter needs to be set for all time clusters. In #829, `tv` was set before any time cluster was even created—and thus no time cluster got the `tv` value (instead, they got `tv=0`). Also, `tpv12_13` gives the expected plasticity value from before #829.
> Re-order tv init and time cluster creation

- .ci/format.sh
- src/Initializer/InitProcedure/InitModel.cpp
- src/Initializer/InitialFieldProjection.cpp
- src/Initializer/tree/LTSSync.hpp
Fixes another bug caused by the initialization re-ordering by #829: the initial conditions were behaving a bit off. To be exact, duplicates in the LTS tree were not initialized for initial conditions, since an Lut lookup was used for that (and to my knowledge, it's the last place where that was the case). Now, we just synchronize the LTSTree after initializing the data. (if someone wants to, we could transform it into a loop over the LTSTree eventually)
> Synchronize LTSTree after Setup of the Initial Conditions

- src/Equations/poroelastic/Kernels/Time.cpp
Just as the title says, in the poroelastic `Time.cpp`, we have under rare circumstances (such as before a sync) that some temporary array `ZinvData` is stack-allocated and pointed to for the kernel. But before the kernel gets executed, the array goes out of scope, since it is defined inside an `if`. This PR fixes that by moving the execution inside the `if` as well.
> Fix `ZinvData` being used after going out of scope

- Documentation/parameters.par
- src/Initializer/InitProcedure/Init.cpp
- src/Initializer/InitProcedure/InitIO.cpp
- src/Initializer/InitProcedure/InitMesh.cpp
- src/Initializer/InitProcedure/InitModel.cpp
- src/Initializer/InitProcedure/InitSideConditions.cpp
- src/Initializer/InputParameters.cpp
- src/Initializer/InputParameters.hpp
The `FaultOutputFlag` had not effect anymore, so it could be safely removed.
Also, `BC_dr` did not work anymore, so it is now gone as well (we now always scan the mesh for any existing faults). With that, the `Boundaries` section has become obsolete.
Furthermore, some files get some anonymous namespaces around their static methods.
> Remove `FaultOutputFlag` and `BC_dr` Input Parameters

- gitlab-cpu-pipeline.yml
- gitlab-gpu-pipeline.yml
Makes the Gitlab pipelines work.
Internally, we moved the CPU pipeline to the SCCS CI node now.
Also, the single stages are now using different node configurations.
But still, right now there are dependencies of the CPU version to be build with the respective CPU features (due to the doctest CMake script requiring them—I might file an issue for that; and the GPU version needs a CUDA runtime available which may become dificult, for now)
> Update Gitlab pipelines

- Documentation/fault-output.rst
- Documentation/parameters.par
fix typo in fault-output.rst
fix mistake in parameters.par example
> Fix typo in documentation

- .gitlab-ci.yml
Fixes the post-build section. (or rather, should do that)
> Change the doxygen build CI instance

- gitlab-gpu-pipeline.yml
The GPU pipeline fails quite often due to these errors, e.g. https://gitlab.lrz.de/ci_seissol/SeisSol/-/jobs/6640476
This PR makes the pipeline more robust, as it allow retries. Maybe 3 tries would be even better.
> Allow retry for GPU build

- CMakeLists.txt
When I was building SeisSol with ASAGI, I got the following errors:
```
[100%] Linking CXX executable SeisSol_Release_dhsw_4_viscoelastic2
ld: cannot find -lpnetcdf
ld: cannot find -lhdf5_hl
ld: cannot find -lhdf5
```
This PR fixes that, as it doesn't require the static ldflags. We properly link the required hdf5/netcdf libraries elswhwere in SeisSol.
> Improve ASAGI cmake

- src/Monitoring/FlopCounter.cpp
Right now, each rank tried to create the FLOP counter file (all with the same file name) and write its header, while only rank 0 would fill it with data later on. This PR fixes that by creating the file only on rank 0.
> Only create FLOP counter file for rank==0

- gitlab-cpu-pipeline.yml
- gitlab-gpu-pipeline.yml
Default time span is 30 days; seemingly accumulating too much memory in total.
Thus, we now set the duration of all artifacts to 2 days.
> Add (shorter) CI expiration time span for artifacts

- src/Parallel/Pin.cpp
Title says it all. We have communicators allocated each time the communication thread gets re-started, but they never get deleted.
> Remove new sharedmem comm allocation for node mask

- cmake/FindLIBXSMM.cmake
SeisSol calls find_package(LIBXSMM) twice if GEMM_TOOLS_LIST is omitted, but that is illegal as add_library is called twice. This PR fixes the LIBXSMM find script such that add_library is only called once should the find script be invoked multiple times.
> Update find libxsmm

- CMakeLists.txt
- Documentation/installing-dependencies.rst
- cmake/FindPSpaMM.cmake
- generated_code/generate.py
As the title says, if libxsmm or Pspamm are found by CMake, they may not be found by Yateto, because CMake may find them somewhere on the system; e.g. if the `CMAKE_PREFIX_PATH` contains a location which is not contained `PATH` variable.
Thus, this PR fixes that. Also, we prepare PSpaMM for https://github.com/SeisSol/PSpaMM/pull/8 (interestingly, that did not require any CI fixing, as it wasn't used there anywhere in any way).
> Propagate Libxsmm and PSpaMM path from CMake to the generator scripts / Yateto

- src/Solver/FreeSurfaceIntegrator.cpp
Alignment in yateto does not match alignment in cmake/process_users_input.cmake. Therefore, the code in initializeProjectionMatrices had an out-of-bounds write. Fix in this PR.
> Fix bug in free surface integrator that occurs if SeisSol alignment != yateto alignment

- src/Initializer/BatchRecorders/PlasticityRecorder.cpp
- src/Initializer/LTS.h
- src/Kernels/Plasticity.cpp
- src/ResultWriter/EnergyOutput.cpp
- src/Solver/time_stepping/TimeCluster.h
Fixes #984 . Also, we remove references to `NUMBER_OF_ALIGNED_BASIS_FUNCTIONS` and replace them with the proper tensor sizes, to avoid potential future errors.
> Adjust tensor sizes to fix plasticity error

- gitlab-cpu-pipeline.yml
- gitlab-gpu-pipeline.yml
- src/DynamicRupture/Parameters.h
- src/Initializer/InputAux.hpp
Require that the friction law parameters are specified in the parameter file, and do not use default values if not found.
> fail if dynamic rupture parameters not find

- postprocessing/visualization/tools/extractDataFromUnstructuredOutput.py
important change is the following:
```
parser.add_argument(
"--time",
nargs=1,
default=["i:"],
help=(
"simulation time or steps to extract, separated by ','. prepend a i for a step,"
" or a python slice notation. E.g. 45.0,i2,i4:10:2,i-1 will extract a snapshot"
" at simulation time 45.0, the 2nd time step, and time steps 4,6, 8 and the"
" last time step"
),
)
```
Example:
```
(base) ulrich@ulrich-ThinkPad-T490s:~/trash$ python ~/SeisSol/SeisSol/postprocessing/visualization/tools/extractDataFromUnstructuredOutput.py ./Tohoku_thrust_2d_plast_all_mu_dep_resampled-fault.xdmf --Data "ASl" --time "2.0,i13,i-1,i20,i20:40"
done writing Tohoku_thrust_2d_plast_all_mu_dep_resampled_resampled-fault_vertex.h5
ASl 0 1 2 3 4 5 6 7 8 9 10
11 12 13 14 15 16 17 18 19 20
21 22 done writing …
```
> change time step selection of extractDataFromUnstructuredOutput.py

- Documentation/frontera.rst
- Documentation/supermuc.rst
On Frontera, we are ask to copy and load the dynamic libraries to scratch, rather than loading them from work (e.g. through spack or the module command). I dug info from slack, that I propose putting it here.
Note that there might be a problem on how impalajit is linked to seissol.  Therefore the manual add.
Here is an example of outcome of the ldd command.
```
ulrich@login4:/scratch1/09160/ulrich/Turkey-Syria-Earthquakes/SeisSolSetupHeterogeneities/event2$ ldd ../../../SeisSol/build/SeisSol_Release_dskx_6_viscoelastic2
linux-vdso.so.1 =>  (0x00007ffcdd3e3000)
/opt/apps/xalt/xalt/lib64/libxalt_init.so (0x00002b775dbe1000)
libasagi.so.1 => /work2/09160/ulrich/frontera/spack/opt/spack/linux-centos7-cascadelake/intel-19.1.1.217/asagi-1.0.1-orizcqekhmhoqvcvyfxaciknepzznzze/lib/libasagi.so.1 …
```
> detail the dumping of dynamic libraries

- src/DynamicRupture/Output/ReceiverBasedOutput.cpp
- src/Initializer/InitialFieldProjection.cpp
- src/Initializer/preProcessorMacros.hpp
- src/ResultWriter/AnalysisWriter.cpp
- src/ResultWriter/EnergyOutput.cpp
- src/Solver/FreeSurfaceIntegrator.cpp
NVHPC currently incorrectly implements some of the OpenMP clauses used in SeisSol—hence this PR to disable OpenMP at these places entirely. However, we introduce a flag in this PR that will probably enable the OpenMP clauses, once the bug has been fixed in NVHPC.
Supersedes #526 .
> Disable Some OpenMP Clauses for NVHPC

- Documentation/performance-measurement.rst
The performance metric documentation was a bit outdated (due to #829 , probably) and contained a misleading relationship between the HW-FLOP and NZ-FLOP values. Thus, we rewrite the page a bit.
> Update the Performance Metric Documentation

- src/Solver/time_stepping/MiniSeisSol.cpp
Lets some builds fail—hence we remove it.
Ported from #1003 .
> Remove superfluous include

- gitlab-gpu-pipeline.yml
- src/DynamicRupture/Output/OutputManager.cpp
- src/DynamicRupture/Output/ReceiverBasedOutput.cpp
- src/DynamicRupture/Output/ReceiverBasedOutput.hpp
Right now, the pickpoint fault output will allocate new memory far too often, as introduced by #1001 (thus slowing down the performance generally), thus the performance suffers.
This PR fixes that (in fact, if the fault output is enabled, we now get an even higher performance than with USM—as tested on HomeOne at least).
Also, we fix the GPU pipeline.
> Remove Unnecessary Fault Output Allocations

- .gitlab-ci.yml
Recent changes (#1017) required an update of the version number.
> Bump cpu image version

- src/DynamicRupture/Output/Builders/ReceiverBasedOutputBuilder.cpp
> Adjust fault face indexing to not iterate over an `std::map` for each lookup

- .github/workflows/github-to-gitlab-push-sync.yml
ChEESE-2 collaborates with the CASTIEL-2 COE to gather all European exascale codes in a centralized gitlab at HLRS.
This PR sets up a push mirror from this github repository to the gitlab mirror.
> Set up HLRS codehub mirror

- .ci/docker-gpu/Dockerfile.base
- .ci/docker-gpu/Dockerfile.compilers
- .gitlab-ci.yml
- gitlab-cpu-pipeline.yml
- gitlab-docker-images.yml
- gitlab-gpu-pipeline.yml
The image building now works again, thanks to replacing `docker build` by a call to Kaniko, basically building Docker images without a Docker socket in the background (so we don't have to install Docker on the CI node). With that, we've also fully ported our CI to the SCCS CI systems.
Also, we now only re-build the image, if the version number gets updated (and by nothing else). That's mostly to prevent the long times when re-building the GPU compiler image by accident.
> Replace Docker builds by Kaniko

- src/DynamicRupture/Output/FaultRefiner/FaultRefiners.cpp
- src/DynamicRupture/Output/FaultRefiner/FaultRefiners.hpp
#1046 has revealed that omitting the `fault_refiner´ flag in the parameter file (or explicitly setting it to _no refinement_), causes SeisSol to crash. This PR adds the "NoRefiner", which just adds one receiver at the barycenter.
> Add NoRefiner

- src/Initializer/Parameters/LtsParameters.h
- src/Initializer/Parameters/ParameterReader.h
- src/Initializer/time_stepping/LtsLayout.cpp
- src/Initializer/time_stepping/LtsWeights/LtsWeights.cpp
- src/Kernels/Receiver.h
- src/Monitoring/ActorStateStatistics.cpp
- src/Monitoring/ActorStateStatistics.h
- src/Monitoring/FlopCounter.cpp
- src/Parallel/Pin.cpp
- src/Physics/InitialField.cpp
- src/ResultWriter/PostProcessor.cpp
- src/Solver/time_stepping/AbstractTimeCluster.cpp
- src/Solver/time_stepping/MiniSeisSol.cpp
- src/Solver/time_stepping/TimeCluster.cpp
- src/Solver/time_stepping/TimeManager.cpp
Mostly warnings of  this kind:
```
/export/dump/ulrich/myLibs/seissol/src/Initializer/time_stepping/LtsLayout.cpp:57:2: warning: field 'seissolParams' will be initialized after field 'm_cellClusterIds' [-Wreorder-ctor]
57 |  seissolParams(parameters),
|  ^~~~~~~~~~~~~~~~~~~~~~~~~
|  m_cellClusterIds(           NULL )
58 |  m_cellClusterIds(           NULL ),
|  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|  m_globalTimeStepWidths(     NULL )
59 |  m_globalTimeStepWidths(     NULL ),
|  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|  m_globalTimeStepRates(      NULL )
60 |  m_globalTimeStepRates(      NULL ),
|  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|  m_plainCopyRegions(         NULL )
61 |  m_plainCopyRegions(         NULL ),
|  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|  m_numberOfPlainGhostCells(  NULL )
62 | …
```
> fix many clang warnings

- .ci/format.sh
- src/DynamicRupture/Output/Builders/ReceiverBasedOutputBuilder.cpp
- src/DynamicRupture/Output/DataTypes.hpp
- src/DynamicRupture/Output/OutputManager.cpp
- src/DynamicRupture/Output/ReceiverBasedOutput.cpp
- src/DynamicRupture/Output/ReceiverBasedOutput.hpp
- src/Kernels/Receiver.cpp
- src/Kernels/Receiver.h
- src/Parallel/DataCollector.h
- src/ResultWriter/ReceiverWriter.cpp
- src/ResultWriter/ReceiverWriter.h
Unifies the output for the receivers in the DR and the wave propagation part (since: we have a (usually sparse) gather operation of some device memory in both cases).
Plus, less stream/queue syncs for multiple receivers.
> Add a Data Collector Class

- Documentation/supermuc.rst
In this PR, I refactor the supermuc documentation page, now detailing how to install the seissol spack package.
I nevertheless keep information about how to compile seissol-env.
On NG, there are two user_spack packages. 
One with spack 0.17.1 (extremly old) and another with spack 0.22.0.dev0.
seissol-env was installed with  0.17.1.
It is tricky to install the new seissol package based on this version (too modern).
On the other hand, I have trouble getting workable modules with spack 0.22.0.dev0.
E.g. module of dependencies do not get created (easi), even if I manually try to create them (it works on heisenbug).
Anyway, this is not such a big issue (e.g. the easi python module I was needing can be using by manually adding the path to the library to PYTHONPATH).
That's why I still detail …
> Refactor supermuc documentation page

- src/DynamicRupture/Output/ReceiverBasedOutput.cpp
This works now but the P_n0 on the fault receivers look a little more different from the reference. But the reference has the wrong implementation for dynamic rupture receiver output too. So, I think it makes sense to update the precomputed repository with this updated calculation after the PR is merged.
> alpham fixed in Receiver output

- Documentation/fault-tagging.rst
- src/Initializer/InitProcedure/InitMesh.cpp
Fix/address #1083.
We add an option to check for an attribute in a PUML file which gives us the boundary type. Otherwise, we avoid `i64`, unless specified explicitly.
> Change boundary format inference rules

- Documentation/dynamic-rupture.rst
- Documentation/parameters.par
- src/DynamicRupture/FrictionLaws/GpuImpl/LinearSlipWeakening.h
- src/DynamicRupture/FrictionLaws/LinearSlipWeakening.cpp
- src/Initializer/Parameters/DRParameters.cpp
(it was either I change the documentation and move the denominator to the numerator in the equation: 
or changing the sign of alpha in the code. I propose changing the code, as the formula looks clearer like that.)
> harmonize documentation and code regarding tpProxyExponent

- src/Initializer/InitProcedure/InitIO.cpp
- src/Initializer/InitProcedure/InitModel.cpp
We had a barrier in an `if` when creating the output directories. Now if one rank was slower than all others and happened to check for directory existence after it had already been created, it would skip that very barrier, causing a desync in the whole MPI communication. Thus, we put the barrier outside the if.
Also, we fix two typos on OpenMP pragma statements.
Thanks goes to @montrie for finding these issues.
> Fix Hangup When Creating Folder for IO

- Documentation/lumi.rst
The currently-described setup uses ROCm 5.6 which seems to be broken with `HSA_XNACK=1`.
#1016 will remedy the performance anyways.
> Recommend disabling `HSA_XNACK` for the current LUMI run instructions

- src/ResultWriter/EnergyOutput.cpp
- src/ResultWriter/EnergyOutput.h
Instead of allocating and de-allocating pinned memory at each sync point, we allocate it at the start of the simulation.
That should improve the performance with frequent synchronization points.
> Allocate Buffer for Energy/DR Output Only Once

- auto_tuning/proxy/src/proxy_seissol_integrators.hpp
The title says it all. There were some changes over the years which made the proxy not compile without OpenMP—so we fix them.
> Make the Proxy compile without OpenMP

- CMakeLists.txt
- src/Solver/FreeSurfaceIntegrator.cpp
- src/Solver/time_stepping/TimeCluster.cpp
Load yaml-cpp libraries from CMake starting with yaml-cpp version 0.8, instead of specifying the file explicitly.
(note that the `yaml-cpp` CMake seems to be à priori using the library name instead of a path when querying the `YAML_CPP_LIBRARIES` variable directly)
Also, we move two `alignas` attributes (?) which weren't moved by #1133 .
(note that for this patch to work will also require `easi` to be recompiled. Then the explicitly-needed `LIBRARY_PATH`/`LD_LIBRARY_PATH` specification can be left away.)
> Include the CMake `yaml-cpp::yaml-cpp` library list, not the file itself

- src/Initializer/InitProcedure/InitMesh.cpp
Fixes a segfault if the given boundary format string is a fixed (and not variable) Hdf5 string.
(cf. https://github.com/SeisSol/PUMGen/pull/76 to fix that problem on the PUMgen side as well, in particular for v1.1.4)
> Allow parsing for fixed-length strings for the boundary format

- cmake/FindGemmTools.cmake
- cmake/process_users_input.cmake
- generated_code/generate.py
We add an explicit `none` option to the GEMM tools list (which gets ignored during gemm tool finding).
(note that it was possible right now already implicitly ; e.g. when using `noarch` together with `PSpaMM` )
> Allow CPU Codegen without GEMM Tools

- src/Parallel/Helper.hpp
@davschneller please feel free to reject it if we are not ready to use Persistent MPI by default everywhere
> Use Persistent MPI by default

- src/Initializer/InitProcedure/InitMesh.cpp
As discussed in #1154, there were sometimes still null characters at the end of the read boundary condition strings. This PR caps the string at the first 0.
> Fix considering trailing zero characters in fixed-length strings for boundary inference

- .ci/gha-cpu/Dockerfile
- .github/workflows/build-image.yml
- .github/workflows/build-seissol.yml
Replace the always-running dependency build with a Docker image, thus removing this startup time.
> Add Pre-Build GHA CI Dependency Image

- .ci/format.sh
- .github/workflows/build-image.yml
- .github/workflows/build-seissol.yml
- .github/workflows/clang-format.yml
- .github/workflows/clang-tidy.yml
- .github/workflows/doc-template.yml
- .github/workflows/github-to-gitlab-push-sync.yml
- src/Main.cpp
- src/Parallel/Pin.cpp
- src/Parallel/SyclInterop.h
Pip now offers `clang-format==19.1.0`; hence this PR does the upgrade.
> Upgrade to Clang Format 19

- src/DynamicRupture/Factory.cpp
- src/DynamicRupture/FrictionLaws/BaseFrictionLaw.h
- src/DynamicRupture/FrictionLaws/FrictionLaws.h
- src/DynamicRupture/FrictionLaws/GpuImpl/NoFault.h
Ported from #1122 . Effectively, we only need to copy the traction around (in principle, we could also do that as a memcpy operation, on second thought).
(NOTE: it's different from a "true" DR-disablement—which can also be included in some subsequent PR)
> Add the No-Fault Friction Law for the GPU

- src/DynamicRupture/FrictionLaws/GpuImpl/NoFault.h
#1184 forgot a virtual method, thus breaking the GPU builds. Here's the fix.
> Fix GPU Build

- cmake/process_users_input.cmake
We hide:
* `MPI` (assumed to be always on)
* `OPENMP` (assumed to be always on)
* `HDF5` (assumed to be always on)
* `LOG_LEVEL` (assumed to be `"warning"` for compatibility reasons)
Currently, as in #1185, we don't compile with `MPI=OFF`. The setting `OPENMP=OFF` _could_ maybe work; but is completely untested. Also `HDF5=OFF` would not allow any meshes to be read in at the current point in time (_maybe_ the cube generator would work as standalone).
Also, `LOG_LEVEL` is ignored as of now; only `LOG_LEVEL_MASTER` matters.
> Hide some for-now-always-on options

- src/Kernels/DenseMatrixOpsAARCH64.h
- src/Kernels/DenseMatrixOpsSVE.h
The stream store from #961 actually had a mistake in it (it stream-loaded the data as well... That's fixed now).
> Fix stream store for ARM

- src/Equations/elastic/Kernels/Interface.h
- src/Equations/elastic/Kernels/Time.cpp
- src/Initializer/BatchRecorders/LocalIntegrationRecorder.cpp
- src/Kernels/DynamicRupture.cpp
We change:
* remove a remnant of the circular streams/stream ring buffer (those are now allocated dynamically); and may be removed soon-ish from the Device module
* remove a remnant from a merge conflict which prevented a build without experimental kernels
* fix one host-device buffer usage bug
> Some very tiny bugfixes

- src/Initializer/Parameters/OutputParameters.cpp
Set `pickdt=0.005` if not given (as in the doc parameter file); previously, it had been `0`, causing length error bugs when reserving receiver space.
Furthermore, we now block non-negative `pickdt` values—and interpret them as disabling the receiver recording.
> Set a positive pickdt default

- postprocessing/validation/compare-receivers.py
- src/Equations/anisotropic/Model/Datastructures.h
- src/Equations/elastic/Model/Datastructures.h
- src/Equations/poroelastic/Model/Datastructures.h
- src/Equations/viscoelastic2/Model/Datastructures.h
- src/Initializer/InitProcedure/InitIO.cpp
- src/ResultWriter/WaveFieldWriterExecutor.h
A suggestion. It's to source the variable names entirely from the material class. Right now, that would mean that both receivers and wavefield have (displayed here for poroelastic, since it includes elastic):
```
s_xx, s_yy, s_zz, s_xy, s_yz, s_xz, v1, v2, v3, p, v1_f, v2_f, v3_f, # (poro)elastic
ep_xx, ep_yy, ep_zz, ep_xy, ep_yz, ep_xz, eta # plasticity
```
The only significant change would be that `sigma_xx`, `xx` -> `s_xx` and so on.
> Unify variable names for receivers and wavefield

- src/Initializer/TimeStepping/LtsLayout.cpp
Add
* all clusters that are only present in ghost halos
* all cluster gaps, to make everything contiguous afterwards (to make the actor model happy)
to the local cluster id array. So far, it seemingly only contained all copy/interior cell cluster ids (i.e. those which are really computed on the local rank).
Potential relation to #1181 and #839 .
> Extend Local Cluster Array

- src/DynamicRupture/Output/Builders/PickPointBuilder.h
- src/DynamicRupture/Output/ReceiverBasedOutput.cpp
- src/Initializer/PointMapper.cpp
- src/Initializer/PointMapper.h
Fault receivers located between ghost and copy layers were ignored so far; thus we fix that.
(note that the respective point-to-fault-face assignment code can still need a lot of refactoring)
> Fix fault receivers in halos (between ghost and copy layers)

- src/Initializer/BatchRecorders/DataTypes/Table.h
(caused newer clang versions to fail with the build)
> Fix wrong names in copy constructor

- src/Initializer/InitProcedure/InitMesh.cpp
- src/ResultWriter/ReceiverWriter.cpp
In response to #1226. We
* print all receivers that have not been found. Also, we abort, if that's the case. [NOTE: if you're unhappy with that change, PLEASE protest here. It may be a bit too harsh.]
* print the smallest possible mesh bounding box; that is, the min/max value of all vertices, globally.
> Warn/Fail on Not-Found Receivers, Print Mesh Boundary Box

- .github/workflows/coverage.yml
- CMakeLists.txt
- cmake/CodeCoverage.cmake
- generated-code/generate.py
* Fix generated kernel test generation
* Make the coverage computation work with test drivers (i.e. testing commands, like needed for NVHPC)
* Fix the coverage computation
* Remove the generated kernels and easi from the coverage calculation (feel free to protest here, if it feels wrong to someone)
* Add the coverage computation to the CI (including a downloadable overview)
(note: the coverage is currently pretty low, since we only consider the unit tests here. The full CI should test through much more parts of the code, via the end-to-end tests—it might be useful to somehow integrate those into the unit tests or the coverage computation somehow.)
> Fix the Coverage Computation

- .github/workflows/clang-tidy.yml
- CMakeLists.txt
- auto-tuning/proxy/src/CMakeLists.txt
- auto-tuning/proxy/src/Proxy/CMakeLists.txt
- src/IO/CMakeLists.txt
- src/cuda.cmake
- src/hip.cmake
- src/sources.cmake
- src/sycl.cmake
...to: kebab case (all lowercase). B/c it's easier to type. (also, some parts like `seissol-io` are already in that style)
[note: the exported target names don't change—those are set explicitly; however, we can of course do that as well]
> Normalize CMake Target Names

- .github/workflows/build-seissol-cpu.yml
The CPU CI unit tests currently take a long time, and some tests still fail.
Still, we hereby enable them on the master branch for now.
> Enable CPU CI unit tests for the master branch

- src/Monitoring/FlopCounter.cpp
The NZ-HW-FLOP ratio is a good measure to see how much "useful" work is getting done. Hence, we display it at the end of the simulation.
Not super happy with the name "NZ part of HW-FLOP" yet—if you have better suggestions, I'd be happy to hear them. :)
> Display the NZ-HW-FLOP ratio (as percentage)

- src/DynamicRupture/FrictionLaws/FastVelocityWeakeningLaw.h
- src/DynamicRupture/FrictionLaws/GpuImpl/FastVelocityWeakeningLaw.h
Replace the `exp(x) - exp(-x)` by `sinh` again—since the former is inaccurate for `x` close to 0—and might yield negative values there. Thus breaking the subsequent `log` application.
Possibly related to #361 and #342.
> Reduce some numerical errors in the FVW calculation

- Documentation/parameters.par
- gitlab-cpu-pipeline.yml
- gitlab-gpu-pipeline.yml
- src/DynamicRupture/FrictionLaws/BaseFrictionLaw.h
- src/DynamicRupture/FrictionLaws/FrictionSolverCommon.h
- src/DynamicRupture/FrictionLaws/GpuImpl/BaseFrictionSolver.h
- src/Initializer/Parameters/DRParameters.cpp
- src/Initializer/Parameters/DRParameters.h
Please take a look at the comment in the code.
Need to be in-depth tested, but my first tests seem to confirm it works better (no more/less trailing signal).
Any comment is welcome
Thomas.
> Mw from slipRateMagnitude based on slipRate1 and 2 (and not the across interface velocities)

- Documentation/gpus.rst
- src/Initializer/MemoryManager.cpp
Added in #923, it was added to mitigate some bugs on LUMI with old ROCm (early/mid 5) back then. However, those should be fixed by now. Hence, we remove it.
> Remove some legacy code

- src/DynamicRupture/FrictionLaws/BaseFrictionLaw.h
- src/DynamicRupture/FrictionLaws/FrictionSolverCommon.h
- src/DynamicRupture/FrictionLaws/GpuImpl/AgingLaw.h
- src/DynamicRupture/FrictionLaws/GpuImpl/BaseFrictionSolver.h
- src/DynamicRupture/FrictionLaws/GpuImpl/FastVelocityWeakeningLaw.h
- src/DynamicRupture/FrictionLaws/GpuImpl/FrictionSolverDetails.cpp
- src/DynamicRupture/FrictionLaws/GpuImpl/FrictionSolverDetails.h
- src/DynamicRupture/FrictionLaws/GpuImpl/FrictionSolverInterface.h
- src/DynamicRupture/FrictionLaws/GpuImpl/LinearSlipWeakening.h
- src/DynamicRupture/FrictionLaws/GpuImpl/NoFault.h
- src/DynamicRupture/FrictionLaws/GpuImpl/RateAndState.h
- src/DynamicRupture/FrictionLaws/GpuImpl/SlipLaw.h
- src/DynamicRupture/FrictionLaws/GpuImpl/SlowVelocityWeakeningLaw.h
- src/DynamicRupture/FrictionLaws/GpuImpl/ThermalPressurization/NoTP.h
- src/DynamicRupture/FrictionLaws/ImposedSlipRates.h
- src/DynamicRupture/FrictionLaws/LinearSlipWeakening.h
- src/DynamicRupture/FrictionLaws/NoFault.cpp
- src/DynamicRupture/FrictionLaws/NoFault.h
- src/DynamicRupture/FrictionLaws/RateAndState.h
- src/DynamicRupture/Typedefs.h
- src/tests/DynamicRupture/FrictionLaws/FrictionSolverCommon.t.h
Merge all DR kernels on the GPU; thus reducing the amount of temporary memory needed and reducing the launch overhead. Also, we're able to keep more temporary variables in registers.
Preliminary tests for LSW (precomputed-seissol/tpv5, on my laptop; RTX 3070 mobile—there's probably similar behavior on at least all gaming cards) show a speedup of around 2× for the LSW DR kernels. The R+S kernels show less speedup (however: maybe that's due to the FP64 performance of the card used), most show ~no speedup at all~ [correction: they also seem to show something about 1.2-1.3×]; but FVW has something around 1.3×.
Tested with precomputed-seissol; there tpv5, tpv6, tpv101, tpv101-slip, tpv104 by comparing the energy values.
EDIT: now also pre-computed some values in the R+S fixed-point iteration …
> Merge the DR Kernels

- src/DynamicRupture/Initializer/BaseDRInitializer.cpp
- src/Initializer/InitProcedure/InitModel.cpp
- src/Initializer/ParameterDB.cpp
- src/Initializer/ParameterDB.h
- src/Initializer/Parameters/LtsParameters.cpp
- src/Initializer/Parameters/ModelParameters.cpp
- src/Initializer/Parameters/ModelParameters.h
- src/Initializer/Parameters/SeisSolParameters.cpp
- src/Initializer/TimeStepping/GlobalTimestep.cpp
- src/Main.cpp
That is:
* print the precision built with
* print the flux used for the run
* remove the old yes/no model printing inherited from the FORTRAN code, and replace it by checking `MaterialT::Text` instead
> Refactor model info printing a tiny bit

- src/Initializer/Parameters/OutputParameters.cpp
- src/Initializer/Parameters/ParameterReader.h
Other than that, nothing should change.
I.e. now we check:
* `output/wavefieldoutput` exists -> use its value (ignore `output/format`)
* if not, and `output/format` exists -> use its value, and warn that it's deprecated
* otherwise, the volume output is off.
(before, it was: `output/wavefieldoutput` and `output/format` both need to be enabled; while the former was enabled by default, and the latter disabled)
> Disable the volume output by default

- src/Kernels/DenseMatrixOps.h
- src/Kernels/DenseMatrixOpsAARCH64.h
- src/Kernels/DenseMatrixOpsSVE.h
(broken by the header normalization, fixed here)
> Fix the build for ARM/NEON/SVE

- src/Initializer/BasicTypedefs.h
- src/Proxy/KernelDevice.cpp
- src/Solver/time_stepping/TimeCluster.cpp
Currently, the predictor consists of two graphs; a large one and a short one, with a potential boundary application in between. However, both of them can be merged by moving the boundary application onto the GPU as well (which has been done by #1016 ).
> Merge the two graphs in the predictor into one

- src/Initializer/CellLocalMatrices.cpp
Enforce Godunov boundaries at:
* elastic-acoustic boundaries
* outflow boundaries
(not 100%ly sure if the latter is really necessary)
> Enforce more Godunov boundaries (when Rusanov is chosen)

- .github/workflows/build-seissol-cpu.yml
- .github/workflows/build-seissol-gpu.yml
- postprocessing/validation/compare-energies.py
- src/ResultWriter/EnergyOutput.cpp
- src/ResultWriter/EnergyOutput.h
The energy output and CI verification broke by #385. Thus, we fix it here.
Besides, we merge some MPI calls, and enable the energy output for all equations. (and print a warning if the energy is probably computed inaccurately)
> Fix the energy output

- src/Initializer/TimeStepping/LtsWeights/LtsWeights.cpp
(the maximum difference enforcement was currently skipped, if the wiggle factor did not enforce it)
> Fix non-maxdiff-enforce wiggle

- src/Initializer/ParameterDB.cpp
- src/Initializer/TimeStepping/LtsLayout.cpp
- src/Solver/FreeSurfaceIntegrator.cpp
- src/Solver/FreeSurfaceIntegrator.h
Transform #396 to utilizing the SeisSol memory allocator methods; which should fix the problems—as in all other cases (yes, we could modify the unique pointer with a C++-style allocator here—probably not yet worth the effort; maybe soon). The problem may have lied with using a C++ `delete` onto a `posix_memalign` allocation.
Fix #396
(further formatting of the `Solver` folder will be done by #1122)
> Fix assert, fix #396

- src/Kernels/PointSourceCluster.h
- src/Kernels/PointSourceClusterCudaHip.cpp
- src/Kernels/PointSourceClusterOnHost.cpp
- src/Kernels/PointSourceClusterSycl.cpp
- src/SourceTerm/Manager.cpp
- src/SourceTerm/Typedefs.h
Instead of storing the original point source index, store the simulation it is used in—that's all we need.
Reason: we can avoid one modulo.
(still, IMO the fused way of point source distribution is pretty inconsistent with running a single simulation tbh)
> `fusedOriginalIndex` -> `simulationIndex`

- src/DynamicRupture/Output/OutputManager.cpp
- src/DynamicRupture/Output/ReceiverBasedOutput.cpp
Simple renaming of loop variables as the same loop variable is used as a variable for the outer loop and inner loop. Just creates a small confusion when debugging things.
> Renaming of loop indices in DR output manager and Receiver output

- src/ResultWriter/EnergyOutput.cpp
The plastic moment is currently being printed twice; the second time even if it wouldn't be even computed.
> Remove duplicate plastic moment output

- Documentation/parameters.par
- src/Initializer/InitProcedure/InitSideConditions.cpp
- src/Initializer/Parameters/InitializationParameters.cpp
- src/Initializer/Parameters/InitializationParameters.h
Add a flag to use the initial conditions only for the analytical boundary conditions, and not the initial field.
> Add an `avoidic` flag

- src/Kernels/Plasticity.cpp
- src/Kernels/Plasticity.h
- src/Solver/time_stepping/TimeCluster.h
Includes the latest `Device` updates (NVTX package finding; fix the reduction on CDNA).
Also now uses a 64-bit accumulator for plasticity FLOP during a phase.
> Use larger yield accumulators

- src/Geometry/MeshReader.cpp
- src/IO/Datatype/MPIType.cpp
Types may be sized differently than the elements they store; it can be fixed by resizing the datatype explicitly—cf. https://stackoverflow.com/a/33624425 .
> Add MPI resize to struct types

- CMakeLists.txt
- src/Solver/TimeStepping/ActorState.cpp
- src/Solver/TimeStepping/TimeCluster.cpp
Unfortunately, #1386 went into the right direction; but ran the output twice—once for the interior, once for the copy layer. Thus: strategy switch; we now "emulate" the DR scheduler to run, even if it doesn't have any DR faces.
I've tested it with tpv13-fused locally, and it seems to work—whereas the current master does explicitly _not_ work.
> Fix fault output interval, take 2

- src/DynamicRupture/Output/OutputAux.cpp
- src/DynamicRupture/Output/OutputManager.cpp
- src/Geometry/PUMLReader.cpp
- src/IO/Reader/File/Hdf5Reader.cpp
- src/Initializer/CellLocalMatrices.cpp
- src/Kernels/Receiver.cpp
- src/Physics/InitialField.cpp
* Make ICC builds work (again). Could be done by removing a non-performance critical `constexpr`.
* Fix receiver timing in a cell; i.e. with very small receiver timing. Actually a bug from #1374 which borrowed from the STP implementation. (I'm sorry—again)
* Fix some more compiler warnings that appeared in the meantime
> Fix ICC Builds, receiver timing and some compiler warnings

- Documentation/conf.py
- Documentation/related-publications.rst
- README.md
Forward the new "How To Cite" page to:
* the README
* the readthedocs
Also, a tiny bit of README cleanup. Furthermore, we remove the duplicate (and outdated) publication list from the readthedocs (and thus also the SeisSol repository).
> Forward the "How To Cite" to the README and the Docs
