src/Geometry/refinement/MeshRefiner.h, src/Numerical_aux/typesdef.f90, src/Reader/readpar.f90, src/ResultWriter/WaveFieldWriter.cpp, src/ResultWriter/WaveFieldWriter.h, src/ResultWriter/WaveFieldWriterC.cpp, src/ResultWriter/WaveFieldWriterExecutor.h, src/ResultWriter/inioutput_seissol.f90, src/Solver/Interoperability.cpp, src/Solver/Interoperability.h, src/Solver/f_ftoc_bind_interoperability.f90
Using the `OutputRegionBounds` parameter, under the `&Output` heading, in the `parameter.par` file the user can define the region for which the output is to be written.
This region is provided in the following format
`OutputRegionBounds = xMin xMax yMin yMax zMin zMax`
=> Output a sub-region specified by the user

src/ResultWriter/WaveFieldWriter.h
I was under some other impression when I wrote this.
Since the box is oriented along the axes this simple test works.
=> Simplify vertexInBox

src/ResultWriter/WaveFieldWriter.cpp, src/ResultWriter/WaveFieldWriter.h
The index was out of bounds. Also, the index 2 was not being considered. This also fixes the bug that was introduced #27.
Apologies for the stupid mistake and the panic that ensued.
=> Fix indexing error

src/Reader/readpar.f90
Remove the namelist for post processing and include the integration mask in the Output namelist
=> Remove post processing namelist

.travis.yml
This pull request fixes the config for travis-ci.
Only changed the installed packages.
See [Success](https://travis-ci.org/krenzland/SeisSol/builds/289996455) for validation.
=> Fix travis config.

src/SeisSol.cpp
In this pull request I add a warning in case of low stack size ulimits.
The reason for this is that on some clusters, the ulimit might change unexpectedly without warning which results in a bug that's quite hard to track down.
Possible discussion points:
1. Do I need to check if I'm compiling on a POSIX compatible system? (E.g. on windows this does not compile)
2. What is a reasonable limit here? I've chosen 2GB but that's pretty arbitrary.
=> Add a warning for low stack size ulimits.

src/Physics/Evaluate_friction_law.f90, src/Reader/readpar.f90
remove LSW2, and move LSW16 (optimized + forced time rupture) to FL=2.
Add instant healing feature (was in former LSW2).
=> Remove lsw16

Documentation/asagi.rst, Documentation/supermuc.rst
Hi, I was not able to compile ASAGI with the hints given.
I found my way to compile ASAGI and updated the docu.
=> Documentation ASAGI Install

Documentation/compilation.rst
Add fPIC flag to netcdf, needed to compile ASAGI.
=> Fix compile flags for netcdf.

src/ResultWriter/WaveFieldWriter.cpp
/src/ResultWriter/WaveFieldWriter.cpp
Startegy > Strategy
=> Fix some typographical error

postprocessing/science/GroundMotionParametersMaps/ComputeGroundMotionParametersFromSurfaceOutput_Hybrid.py, postprocessing/science/GroundMotionParametersMaps/README.md, postprocessing/science/GroundMotionParametersMaps/Supermuc2CommandFileComputeGroundMotions.sh, postprocessing/science/GroundMotionParametersMaps/SupermucNGCommandFileComputeGroundMotions.sh
=> updating ComputeGroundMotionParametersFromSurfaceOutput_Hybrid.py

CMakeLists.txt, src/sources.cmake
Also add warning that you need number of mechanisms > 0 to compile.
=> Add support for viscoelastic(1) to CMake build script

CMakeLists.txt, src/Reader/read_backgroundstress.f90
- Removed bugs
- It's now possible to set e.g. LOG_LEVEL_MASTER=info
=> Fix log level for CMake.

Documentation/compilation.rst
=> Change netcdf download url in docu to mirror

src/Initializer/ParameterDB.cpp, src/Initializer/ParameterDB.h, src/Physics/ini_model_DR.f90, src/ResultWriter/faultoutput.f90, src/Solver/Interoperability.cpp, src/Solver/f_ftoc_bind_interoperability.f90
=> add transient nucleation stress to fault output

CMakeLists.txt, src/Model/common.hpp, src/Solver/Interoperability.cpp
This PR fixes some small issues, which we encountered recently:
* Remove glm include dir from CMake
* Fix Free Surface Godunov state
* CPP/Fortran interoperability array ordering
=> Some small fixes

README.md
Very simple PR to remove a space in README.
=> Make Documentation clickable

postprocessing/visualization/tools/CreateVtkCoastLineFromGmt.py
Sorry for the previous pull request (was not clean).
This is a script for generating a vtk coastline file.
I just did some refactoring to be able to apply a translation on the coordinates.
This does not need a thorough review IMO.
=> refactor script

preprocessing/science/refine_srf.py
This is the script I designed to refine temporally and spatially the kinematic model of Northridge.
Basically create more source points by interpolation, and smooth also the SR.
Needed for the training.
Thomas.
=> add script to refine temporally and spatially a kinematic model

cmake/process_users_input.cmake
=> Added deduction for GEMM_TOOLS_LIST based on arch

preprocessing/meshing/cube_c/SConstruct
* prints from python2 to puthon3 style
=> cube_c: fixed scons

cmake/cpu_arch_flags.cmake, cmake/process_users_input.cmake
(Squash merge please)
Add support for AMD Rome architecture.
No support for Intel compiler (it works theoretically but why would you?)
=> Add support for AMD rome

Documentation/attenuation.rst, postprocessing/science/concatenate_EnF_t.py, postprocessing/visualization/tools/extractDataFromUnstructuredOutput.py
Commit about the dark side of SeisSol.
The hard-limit on the clustering with attenuation (update of the docu).
The moment rate function files :-)
(I just added a small feature to decrease the size of the concatenated moment rate file, as sampled every 1e-5s over 900s it can be 100mb big).
=> Nothing to be proud of

test_singularity.sh, test_singularity_cpu.sh
* CTEST_OUTPUT_ON_FAILURE=1
* removed unnecessary env. vars from pipeline scripts
=> imporved ctest output in case of a failure

postprocessing/visualization/receiver/src/View.py
I added a feature to view L2 Errors with viewrec, when comparing traces.
=> Compute L2 errors in viewrec

postprocessing/visualization/receiver/src/View.py
Hi, after merging #319 Thomas found another issue, which is fixed by this PR.
=> Add sampling space parameter

src/ResultWriter/magnitude_output.f90, src/Solver/calc_seissol.f90
=> fix: split MPI communicator to exclude non DR nodes from the reduce

CMakeLists.txt, cmake/process_users_input.cmake
=> Added ampere arch + impalajit as an external lib. (optionally)

Documentation/left-lateral-right-lateral-normal-reverse.rst
Small correction in the documentation regarding the orientation of the normal vector to the fault given in the example of reference. Some lines were added and the orientation of the normal vector was corrected.
=> Small correction in the documentation

Documentation/supermuc.rst
After the SuperMUC-NG maintenance, some modules have new names. This PR reflects these changes.
=> New Module names for SuperMUC-NG

Documentation/compilation.rst
Now uses fork in our organization
=> Adjust Github repository for PSpaMM

postprocessing/science/GroundMotionParametersMaps/ComputeGroundMotionParametersFromSurfaceOutput_Hybrid.py
in #350 I removed the 'initial=0.' option of cumtrapz, as I thought it is unnecessary.
But it turns out that the array returned is then of size n-1 and not n, which breaks the script.
This PR fixes the issue.
=> fix GME script (cumtrapz)

preprocessing/science/refine_srf.py
=> make some args required and not default

Documentation/adapting-the-cad-model-resolution-using-gocad.rst, Documentation/cad-models.rst, Documentation/generating-a-cad-model-using-gocad-basic-tutorial.rst, Documentation/manually-fixing-an-intersection-in-gocad.rst, Documentation/remeshing-the-topography.rst, Documentation/simmodelerCAD-workflow.rst
PR associated with the renaming of https://github.com/SeisSol/Meshing/pull/20
=> update cad tutorial with new script names

Documentation/compilation.rst, src/Equations/poroelastic/Model/datastructures.cpp
It is a small update.
* updated a reference to yateto
* removed a warning from poroelastic (forgotten semicolon)
* added a reference to chainforge into docu
Please, delete this branch after merging
=> Updated reference to yateto

.gitlab-ci.yml, CMakeLists.txt, cmake/FindGemmTools.cmake, cmake/process_users_input.cmake, generated_code/generate.py, src/Kernels/DeviceAux/hip/PlasticityAux.cpp, src/cuda.cmake, src/hip.cmake, src/sources.cmake, src/sycl.cmake
* removed DEVICE_ARCH, DEVICE_SUB_ARCH pair
* made DEVICE_ARCH, DEVICE_BACKEND pair
=> Changed building system for GPUs

CMakeLists.txt, src/Checkpoint/mpio/Wavefield.h, src/Equations/elastic/Kernels/LocalBase.h, src/Equations/elastic/Kernels/NeighborBase.h, src/Equations/elastic/Kernels/TimeBase.h, src/Initializer/BatchRecorders/DataTypes/ConditionalKey.hpp, src/Initializer/MemoryAllocator.cpp, src/Initializer/MemoryManager.cpp, src/Initializer/tree/Layer.hpp, src/Kernels/Receiver.h, src/Numerical_aux/ODEVector.h, src/Physics/InitialField.h, src/ResultWriter/ReceiverWriter.h, src/Solver/Interoperability.cpp
* added submodules/async via system system
* added -Wno-unused-parameter flag for clang
=> removed warnings of clang@11 compiler

src/Equations/elastic/Kernels/Local.cpp, src/Equations/elastic/Kernels/Neighbor.cpp, src/Equations/elastic/Kernels/Time.cpp, src/Equations/poroelastic/Kernels/Time.cpp, src/Equations/viscoelastic2/Kernels/Local.cpp, src/Equations/viscoelastic2/Kernels/Neighbor.cpp, src/Equations/viscoelastic2/Kernels/Time.cpp, src/Kernels/DynamicRupture.cpp, src/Solver/time_stepping/TimeCluster.h
=> Remove #pragma message

postprocessing/visualization/tools/CreateVtkCoastLineFromGmt.py
Updates on the script that allows outputting the coastline in ParaView.
(e.g. I needed the geocent projection).
=> update coastline script

Documentation/parameters.par
See: https://github.com/SeisSol/SeisSol/blob/master/src/Reader/readpar.f90#L2218
Sorry!
=> Fix name of vertexWeightFreeSurfaceWithGravity

Documentation/compilation.rst
1) Link was formatted incorrectly
2) Now link directly to installation section
=> Fix link to easy install

postprocessing/science/GroundMotionParametersMaps/ComputeGroundMotionParametersFromSurfaceOutput_Hybrid.py, postprocessing/visualization/tools/extractDataFromUnstructuredOutput.py
1. Update ground motion script with new velocity names.
2.  In the script to extract time steps from a SeisSol output, Put all the filtering behind an if statement.
This is because this instruction:
```myData = sx.ReadData(args.Data[ida], idt=i)[ids]```
is much slower (x20?) than this one:
```myData = sx.ReadData(args.Data[ida], idt=i)```
3. use a derived class from seissolxdmf to be able to extract directly SR as sqrt(SRs**2+SRd**2)
=> update python extractor

.gitlab-ci.yml, src/DynamicRupture/FrictionLaws/AgingLaw.cpp, src/DynamicRupture/FrictionLaws/AgingLaw.h, src/DynamicRupture/FrictionLaws/FastVelocityWeakeningLaw.cpp, src/DynamicRupture/FrictionLaws/FastVelocityWeakeningLaw.h, src/DynamicRupture/FrictionLaws/RateAndState.h, src/DynamicRupture/FrictionLaws/SlipLaw.cpp, src/DynamicRupture/FrictionLaws/SlipLaw.h, src/DynamicRupture/FrictionLaws/SlowVelocityWeakeningLaw.h
With this PR, I make the slip and aging laws functional in our cpp port.
=> slip and aging laws

Documentation/asagi.rst, Documentation/supermuc.rst
I've updated the modules in the documentation.
Specifically, I suggest now using hdf1.10.
=> upgrade superNG installation documentation

src/DynamicRupture/FrictionLaws/BaseFrictionLaw.h, src/DynamicRupture/FrictionLaws/FrictionSolver.h, src/DynamicRupture/FrictionLaws/ImposedSlipRates.cpp, src/DynamicRupture/FrictionLaws/NoFault.cpp, src/Initializer/DynamicRupture.h, src/Solver/time_stepping/TimeCluster.cpp
Removed large stack allocations from dr/cpp
=> Removed large stack allocations from dr/cpp

src/Numerical_aux/typesdef.f90
=> fix uninitialized ThermalPress variable

src/DynamicRupture/Output/Base.hpp, src/ResultWriter/faultoutput.f90
This commit fixes issue https://github.com/SeisSol/SeisSol/issues/488, using the fortran output. Note that in the cpp implementation, we accumulate the initial stress and the nucleationstress together. Still have to check the cpp output.
=> Fix #488 in fortran output

Documentation/compilation.rst
Correct the PSpaMM symlink in the docs
=> Change Pspamm installation documentation

Documentation/supermuc.rst, postprocessing/science/GroundMotionParametersMaps/ComputeGroundMotionParametersFromSurfaceOutput_Hybrid.py, postprocessing/science/GroundMotionParametersMaps/README.md, postprocessing/science/GroundMotionParametersMaps/requirements.txt
I've been using the script to compute ground motion estimates recently and have been through the installation process of openquake.
I've used the opportunity to update the README.
=> update README from computing ground motion estimate surfaces

src/Kernels/Plasticity.cpp
* Updated reference to Device
* made a slight changes in formatting
=> Updated reference to Device

CMakeLists.txt
Fixes compilation on some systems e.g. Isembard.
=> Use FindPython3 to find python3

Documentation/energy-output.rst
@krenzland I hope you did not address already this point of my review locally.
But I've written the integrals.
=> adding formulas for energy output

src/Solver/time_stepping/TimeCluster.h
=> Fix plasticity.

src/DynamicRupture/Initializers/BaseDRInitializer.cpp, src/DynamicRupture/Initializers/ImposedSlipRatesInitializer.cpp, src/DynamicRupture/Output/Builders/ReceiverBasedOutputBuilder.cpp, src/DynamicRupture/Output/OutputManager.cpp, src/Initializer/MemoryManager.cpp
Use rank in logInfo (avoid having nranks identical lines in the log)
=> use rank in logInfo

Documentation/conf.py, Documentation/energy-output.rst
Also updating language in conf, because of:
```
(base) ulrich@ulrich-ThinkPad-T490s:~/SeisSol/SeisSol/Documentation$ make html
Running Sphinx v5.0.2
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).
loading pickled environment... failed
```
=> fix doc of frictional energy

src/Physics/InitialField.cpp, src/Physics/InitialField.h, src/Solver/Interoperability.cpp
Note: This leads to a small difference in the error (and is conceptually cleaner)
=> Make planar wave structure for acoustic expl

Documentation/reproducible-research.rst
=> add Tinti et al. to reproducible research

src/Solver/time_stepping/TimeCluster.cpp
updated reference to `Device` (see https://github.com/SeisSol/Device/pull/16)
=> Enabled nvtx profiling marks

CMakeLists.txt, azure-pipelines-seissol-template.yml, src/sources.cmake
This PR removes the following code in CMakeLists.txt
https://github.com/SeisSol/SeisSol/blob/f009cf3479fce56b48dc4d3730fd4db4885ae572/CMakeLists.txt#L350-L361
=> Added a common interface cmake target

src/DynamicRupture/FrictionLaws/FrictionSolverCommon.h
Found an issue with the alignment checks in `FrictionSolverCommon.h`
=> Fixed DR-OpenMP offloading version

Documentation/supermuc.rst
=> Fix supermuc example job script

postprocessing/visualization/receiver/src/Filters.py, postprocessing/visualization/receiver/src/View.py, postprocessing/visualization/receiver/src/Waveform.py
- Update uvw -> v1 v2 v3 in filters of viewrec
- Add pick filter to plot only selected components
- Add differentiate filter to compute acceleration from seismograms.
=> Some improvements to viewrec

src/DynamicRupture/Initializers/BaseDRInitializer.cpp, src/DynamicRupture/Initializers/BaseDRInitializer.h, src/Initializer/MemoryManager.cpp, src/Initializer/ParameterDB.cpp, src/Initializer/ParameterDB.h, src/Solver/Interoperability.cpp, src/Solver/f_ftoc_bind_interoperability.f90
Was used on Frontera last night...
=> Fixes 707 (problem during fault initialization)

postprocessing/validation/compare-receivers.py
* Add more command line options to make the tool more versatile
* Consider `u,v,w -> u1,u2,u3` refactoring.
* Some code improvements
=> Improve compare receivers

CMakeLists.txt, src/DynamicRupture/FrictionLaws/GpuImpl/GpuBaseFrictionLaw.h, src/DynamicRupture/FrictionLaws/GpuImpl/LinearSlipWeakening.h, src/DynamicRupture/FrictionLaws/GpuImpl/RateAndState.h, src/Parallel/AcceleratorDevice.cpp, src/Parallel/AcceleratorDevice.h, src/sycl.cmake
=> Fixed compilation for dpcpp

cmake/FindNetCDF.cmake, preprocessing/science/rconv/CMakeLists.txt, preprocessing/science/rconv/README.md
Now you can use `make install` to install rconv and use it everywhere ;-)
=> Add install target to rconv

.ci/run-clang-tidy.py, azure-pipelines-clang-tidy.yml, azure-pipelines-seissol-template.yml, azure-pipelines.yml, src/DynamicRupture/FrictionLaws/FrictionSolverCommon.h, src/DynamicRupture/FrictionLaws/ThermalPressurization/ThermalPressurization.h
* Runtime: 1:14:50s -> 27:02
* Fix warnings
=> Accelerate and fix clang-tidy pipeline

src/Geometry/PUMLReader.cpp, src/Geometry/PUMLReader.h, src/Initializer/ParameterDB.h
Detect errors like in #751 or #778 early and give a proper error message to the user.
Merge after https://github.com/TUM-I5/PUML2/pull/7
=> Include check for mesh correctness

azure-pipelines-clang-format.yml, azure-pipelines-doc-template.yml, azure-pipelines-seissol-template.yml, src/DynamicRupture/FrictionLaws/FastVelocityWeakeningLaw.h, src/DynamicRupture/FrictionLaws/GpuImpl/FastVelocityWeakeningLaw.h
=> FastVelocityWeakeningLaw: real -> double to not lose accuracy + assertion

Documentation/local-timestepping.rst, src/Solver/time_stepping/TimeManager.cpp
=> Fix LTS for rate > 2 when using MPI

Documentation/dynamic-rupture.rst
(to be consistence with the code:
https://github.com/SeisSol/SeisSol/blob/master/src/DynamicRupture/FrictionLaws/LinearSlipWeakening.h#L146)
=> Fixes strength formula in documentation, and code-block

src/Monitoring/ActorStateStatistics.h, src/Monitoring/LoopStatistics.cpp, src/Solver/time_stepping/TimeManager.cpp
- Ignore time spent in actor states in summary
- Remove empty/unused states
- Fix time spent in DR kernels
=> Fix profiling

CMakeLists.txt, Documentation/gpus.rst, src/Common/IntegerMaskParser.cpp, src/Common/IntegerMaskParser.h, src/Parallel/Pin.cpp, src/Parallel/Pin.h, src/SeisSol.cpp, src/sources.cmake, src/tests/Common/IntegerMaskParser.t.h, src/tests/Common/TestCommon.cpp
* Note, it an option for developers
* it can be useful for systems like LUMI, Fugaku
* tests are added
* docu has been updated
@krenzland said that it was ok to implement this feature using an env. variable
=> Added `SEISSOL_FREE_CPUS_MASK` env. variable

CMakeLists.txt
A cleanup of the last remaining FORTRAN compiler-related parts in the CMakeLists file.
=> Cleanup CMakeLists

Documentation/a-first-example.rst, Documentation/compiling-seissol.rst
There were a lot of inconsistencies....
=> Update first example

src/Initializer/InitProcedure/InitMesh.cpp, src/Initializer/InputParameters.cpp, src/Initializer/InputParameters.hpp
Hi all, 
This PR adds an option to display the edge-cut statistics. I personally need it for one experiment. If you think it can be a useful feature then we may consider adding it to the master.
What do you think?
=> Added `showEdgeCutStatistics` option

gitlab-cpu-pipeline.yml, src/tests/Reader/NRFReader.t.h
Was broken by https://github.com/SeisSol/SeisSol/commit/29ce470d0e5bb216e645203c6028deb5d44a83db
=> Fix NRF reader test

Documentation/installing-dependencies.rst, gitlab-gpu-pipeline.yml
* changed paths to gemmforge and chainforge projects
=> Updated docu and gitlab-ci pipelines

src/Initializer/InitProcedure/InitSideConditions.cpp
Fix discovered by https://github.com/vikaskurapati
=> Fix init travelling wave

.gitlab-ci.yml, gitlab-gpu-pipeline.yml
Port doxygen to the SCCS runners.
Also, make GPU performance tests optional.
=> Adjust CI Pipelines (again)

gitlab-cpu-pipeline.yml, postprocessing/validation/compare-energies.py, postprocessing/validation/compare-receivers.py
Add three benchmarks:
* 5-visco: Like TPV5, but with a viscoelastic material.
* 13: standard TPV13 benchmark (plasticity) with a reduced fault size to save compute power
* ahsp: pointsource in anisotropic space
=> More CI benchmarks

src/SourceTerm/Manager.cpp
Potentially related to #957 , cf. the comment https://github.com/SeisSol/SeisSol/issues/957#issuecomment-1727502390
=> Replace `NUMBER_OF_QUANTITIES` by the correct dimension

cmake/cpu_arch_flags.cmake, cmake/process_users_input.cmake, src/Checkpoint/posix/CheckPoint.h, src/Checkpoint/posix/Fault.cpp, src/Checkpoint/posix/Wavefield.cpp, src/Kernels/Plasticity.cpp, src/Monitoring/LoopStatistics.cpp, src/Parallel/Pin.cpp, src/Parallel/Pin.h, src/ResultWriter/ThreadsPinningWriter.cpp, src/Solver/time_stepping/AbstractTimeCluster.cpp
Requires https://github.com/TUM-I5/ASYNC/pull/1 before merging.
Most ifdefs are in Checkpointing (which gets a rewrite quite soon). Other than that, some changes needed to be done in the pinning part.
Can also be used as a template for other non POSIX system. Technically, it doesn't add anything Mac specific, it just removed non-POSIX features. (However, there's
=> Add support for MacOS & M1/M2

Documentation/tpv13.rst
small typo in the doc of tpv13.
Wollherr, S., Gabriel, A. A., & Uphoff, C. (2018). Off-fault plasticity in three-dimensional dynamic rupture simulations using a modal Discontinuous Galerkin method on unstructured meshes: implementation, verification and application. Geophysical Journal International, 214(3), 1556-1584.
=> fixes yield function in tpv13.rst

src/DynamicRupture/Output/Builders/ReceiverBasedOutputBuilder.cpp, src/DynamicRupture/Output/Builders/ReceiverBasedOutputBuilder.hpp, src/DynamicRupture/Output/DataTypes.hpp, src/DynamicRupture/Output/OutputManager.cpp, src/DynamicRupture/Output/ReceiverBasedOutput.cpp, src/Initializer/MemoryManager.cpp, src/Kernels/Touch.cpp, src/ResultWriter/EnergyOutput.cpp, src/Solver/time_stepping/MiniSeisSol.cpp, src/sources.cmake
Adds the fault output for the derivative calculation. (cf. what's been started by #982) We also clean up some SYCL code in the process.
=> Fix GPU fault output

Documentation/related-publications.rst
Remove duplicate related publication
=> Remove duplicate related publication

src/Monitoring/Stopwatch.cpp, src/Monitoring/Stopwatch.h, src/Solver/Simulator.cpp
A small update to output more timing information at each synchronization point.
=> Add more timing infos

src/DynamicRupture/Output/Builders/ReceiverBasedOutputBuilder.cpp
As the title says. The bugfix introduced a bug, hence a bugfix for the bugfix.
=> Fix wrong array indexing (introduced by #1027)

Documentation/energy-output.rst, src/Initializer/typedefs.hpp, src/ResultWriter/EnergyOutput.cpp, src/ResultWriter/EnergyOutput.h
=> add potency output

src/main.cpp
Builds with ASAGI were failing.
=> Add asagi include and add seissol namespace

src/DynamicRupture/FrictionLaws/BaseFrictionLaw.h, src/DynamicRupture/FrictionLaws/FrictionSolverCommon.h, src/DynamicRupture/Misc.h, src/DynamicRupture/Output/ReceiverBasedOutput.cpp, src/Equations/Setup.h, src/Equations/elastic/Kernels/Time.cpp, src/Solver/time_stepping/TimeCluster.cpp, src/tests/DynamicRupture/FrictionLaws/FrictionSolverCommon.t.h
Fix compilation of damaged-elastic model
=> Fix compilation

postprocessing/visualization/receiver/src/View.py, postprocessing/visualization/receiver/src/Waveform.py
We had a differentiate button for some time, now I've added the integration button.
=> Allow integration of quanitities

src/DynamicRupture/Output/ReceiverBasedOutput.cpp, src/Kernels/DynamicRupture.cpp, src/Kernels/Receiver.cpp, src/Kernels/Receiver.h, src/ResultWriter/FreeSurfaceWriterExecutor.cpp, src/Solver/time_stepping/TimeCluster.h
Two fixes, such that the damaged material works in debug builds
=> Damaged material nonlinear hotfixes

Documentation/parameters.par, src/Initializer/CellLocalMatrices.cpp, src/Initializer/CellLocalMatrices.h, src/Initializer/InitProcedure/InitModel.cpp, src/Initializer/Parameters/DRParameters.cpp, src/Initializer/Parameters/DRParameters.h
Adds the patch from #546 as a parameter. Also, we emit a warning if it's used.
=> Add the "eta hack" as a parameter

Documentation/behind_firewall.rst
Add an additional hint, which is needed recently.
=> Add hint for pip installation

src/Kernels/PointSourceClusterOnDevice.cpp
See title. Tested with NVHPC 24.01; it fails without the `constexpr` re-definitions. Reason: cannot be accessed in a device kernel (effectively a compiler bug—but we can circumvent it like that).
=> Add workaround for AdaptiveCpp+NVHPC regarding constexpr arrays in device kernels

src/sources.cmake
Backport of commit dee4915 from #1016. To fix the GPU builds.
=> Add `-fPIC` to CPU kernel lib

gitlab-gpu-pipeline.yml, src/Equations/anisotropic/Model/datastructures.hpp, src/Equations/elastic/Kernels/GravitationalFreeSurfaceBC.h, src/Equations/elastic/Model/datastructures.hpp, src/Equations/poroelastic/Model/datastructures.hpp, src/Initializer/BatchRecorders/LocalIntegrationRecorder.cpp, src/Model/common_datastructures.hpp, src/ResultWriter/EnergyOutput.cpp
A few bugfixes to make anisotropy work on GPUs.
CI tests are included and pass.
=> Make Anisotropic Elasticity Work On GPUs

.github/workflows/build-seissol.yml
Add a mirror for LUA, if it cannot be found.
=> Add LUA mirror

src/Kernels/PointSourceCluster.h, src/Solver/time_stepping/TimeCluster.cpp, src/Solver/time_stepping/TimeCluster.h, src/Solver/time_stepping/TimeManager.cpp, src/Solver/time_stepping/TimeManager.h, src/SourceTerm/Manager.cpp, src/SourceTerm/typedefs.hpp
=> Fix incomplete type for `unique_ptr`

.github/workflows/github-repo-stats.yml
(cf. https://github.com/jgehrcke/github-repo-stats/wiki/Tutorial )
=> Add GH repo stats workflow

src/Parallel/AcceleratorDevice.cpp, src/Parallel/SyclInterop.hpp
Add the coarse-grained event property when AdaptiveCpp is used (and supports it).
=> Add AdaptiveCpp coarse-grained event support

src/Equations/anisotropic/Model/datastructures.hpp, src/Equations/elastic/Model/datastructures.hpp, src/Equations/poroelastic/Model/datastructures.hpp, src/Equations/viscoelastic2/Model/datastructures.hpp
=> Add Includes to Material Files, Fix Quantity Size For `viscoelastic2`

src/Initializer/Parameters/DRParameters.cpp
Previously, the `etahack` parameter was expected in the `output` region; but it's more fitting in the DR region instead.
=> Update etahack reading position

src/DynamicRupture/Factory.cpp, src/DynamicRupture/Factory.h, src/DynamicRupture/FrictionLaws/SourceTimeFunction.cpp, src/DynamicRupture/FrictionLaws/SourceTimeFunction.h, src/DynamicRupture/Initializer/ImposedSlipRatesInitializer.cpp, src/DynamicRupture/Initializer/ImposedSlipRatesInitializer.h, src/Initializer/DynamicRupture.h, src/Initializer/Parameters/DRParameters.cpp, src/Initializer/Parameters/DRParameters.h, src/Numerical/DeltaPulse.h
This PR adds FL 35, which imposes a delta pulse. It should be the basis for a future implementation of numerical Green's functions.
=> Delta pulse friction law

Documentation/meshing-with-simmodeler.rst
add Discrete tab with notes and correct some typos
=> update SimModeler meshing documentation

src/DynamicRupture/Output/OutputManager.cpp, src/Geometry/CubeGenerator.cpp, src/Geometry/NetcdfReader.cpp, src/IO/Datatype/MPIType.cpp, src/Initializer/BatchRecorders/LocalIntegrationRecorder.cpp
* more host-device bugfixes
* fix `MPI_Datatype` and `MPI_Comm` not to use `nullptr` as default value (conflicting e.g. with Intel MPI).
=> Some more small bugfixes

src/Common/Iterator.h
Related to #1209 .
The question would be: would we want to merge it—or request everyone to just use a newer compiler?
Hence draft for now; may be closed.
=> Specify iterator type explicitly

src/DynamicRupture/FrictionLaws/GpuImpl/FastVelocityWeakeningLaw.h, src/DynamicRupture/FrictionLaws/GpuImpl/LinearSlipWeakening.h, src/DynamicRupture/FrictionLaws/GpuImpl/RateAndState.h, src/DynamicRupture/FrictionLaws/ImposedSlipRates.h, src/DynamicRupture/FrictionLaws/LinearSlipWeakening.cpp, src/DynamicRupture/FrictionLaws/LinearSlipWeakening.h, src/DynamicRupture/FrictionLaws/RateAndState.h, src/DynamicRupture/FrictionLaws/SourceTimeFunction.cpp, src/DynamicRupture/FrictionLaws/ThermalPressurization/ThermalPressurization.cpp, src/DynamicRupture/Initializer/ImposedSlipRatesInitializer.cpp, src/DynamicRupture/Initializer/LinearSlipWeakeningInitializer.cpp, src/DynamicRupture/Initializer/RateAndStateInitializer.cpp, src/IO/Instance/Mesh/VtkHdf.cpp, src/Initializer/InitProcedure/InitMesh.cpp
(as appeared with NVHPC; but easily fixable)
=> Fix a few more compiler warnings

src/ResultWriter/WaveFieldWriterExecutor.h
Problem introduced by #1208 , fixed here.
=> Fix volume names by storing the necessary strings

src/Parallel/Runtime/StreamSycl.cpp
The PR adds a port from #1122: the synchronization to AdaptiveCpp may rely on CUDA/ROCm events alone. A bit hacky, but it works.
=> Fix HIP Graphs and Remove Some Synchronization

postprocessing/science/GroundMotionParametersMaps/ComputeGroundMotionParametersFromSurfaceOutput_Hybrid.py
cumtrapz has been deprecated since scipy 1.14.1
=> change deprecated cumtrapz in scipy 1.14.1

LICENSE
=> Update copyright year to 2025

Documentation/heisenbug.rst
updated based on the latest version of the seissol spack package.
=> update heisenbug documentation

cmake/process_users_input.cmake
=> Add sm_101, sm_120 to the architecture list

.github/workflows/build-seissol-cpu.yml, .github/workflows/build-seissol-gpu.yml, src/Reader/AsagiModule.cpp, src/Reader/AsagiModule.h, src/Reader/AsagiReader.cpp, src/Reader/AsagiReader.h
We
* fix #1267 
* apply `clang-tidy` to the SeisSol ASAGI reader files
* enable the build with ASAGI in the CI
=> Format/refactor the SeisSol/ASAGI Connection

src/IO/Instance/Checkpoint/CheckpointManager.cpp, src/IO/Instance/Checkpoint/CheckpointManager.h, src/IO/Reader/Distribution.cpp, src/IO/Reader/Distribution.h, src/IO/Reader/File/Hdf5Reader.cpp, src/IO/Writer/File/Hdf5Writer.cpp, src/Initializer/LTS.h
* Corrected a bug with setting the chunksizes
* Add some code for ignoring padding (disabled for now)
=> Fix the new IO Reader

postprocessing/visualization/tools/CreateVtkCoastLineFromGmt.py
That's a small tool to extract a coastline from gmt and transform it to vtk to vizualization.
I just allow filtering for lakes or small close areas.
=> update coastline tool

Documentation/dynamic-rupture.rst
Minor update to cohesion description (this time as correct PR). Frictional cohesion should act on normal stress, not shear stress.
=> cohesion docs fix

postprocessing/visualization/tools/CreateVtkCoastLineFromGmt.py
added functionality I needed recently for some figures.
=> crop coastline to given box

src/ResultWriter/EnergyOutput.cpp
=> Fix abort criterion

src/Common/Typedefs.h, src/Config.h.in
=> Rename ViscoMode type

src/Monitoring/FlopCounter.cpp, src/Monitoring/Stopwatch.cpp, src/Monitoring/Stopwatch.h, src/ResultWriter/FaultWriterExecutor.h, src/ResultWriter/FreeSurfaceWriterExecutor.h, src/ResultWriter/WaveFieldWriterExecutor.h, src/Solver/Simulator.cpp
In essence, output the mean value in pure seconds, and not also formatted. Also, give the stddev.
Plus a tiny bit of re-formatting.
=> Adjust time output by a very tiny bit

.github/workflows/build-seissol-cpu.yml, .github/workflows/build-seissol-gpu.yml
=> Fix end-to-end tests after renaming

src/DynamicRupture/Output/Builders/ElementWiseBuilder.h
Assign fused indices for the elementwise output as well.
=> Fix elementwise fault output
